### PR TITLE
LPS-91813

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-91813

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test

**Comment by lipusz** [comment]
@holatuwol Looks like I'm still missing something. I committed the JAR and the POM to .gradle cahce, but it's still unable to find. Any idea?

**Comment by lipusz** [comment]
Hey Charles, @CAustin582

@petershin let me know that you could add **`netcdf-4.3.23`** to our Nexus so I can proceed with this fix. Right now `ant all` fails with 

```
     [exec] * What went wrong:
     [exec] Could not resolve all files for configuration ':libPortal'.
     [exec] > Task :setUpLibPortal FAILED
     [exec] 3 actionable tasks: 3 executed
     [exec] Gradle build finished at 2019-03-23 19:55:19.481.
     [exec] > Could not resolve edu.ucar:netcdf:4.3.23.
     [exec]   Required by:
     [exec]       project :
     [exec]    > Could not resolve edu.ucar:netcdf:4.3.23.
     [exec]       > Could not parse POM http://repository-cdn.liferay.com/nexus/content/groups/public/edu/ucar/netcdf/4.3.23/netcdf-4.3.23.pom
     [exec]          > Could not find edu.ucar:thredds-parent:4.3.23.
     [exec]            Searched in the following locations:
     [exec]              - file:/opt/dev/projects/github/liferay-portal/.m2/edu/ucar/thredds-parent/4.3.23/thredds-parent-4.3.23.pom
     [exec]              - file:/opt/dev/projects/github/liferay-portal/.m2/edu/ucar/thredds-parent/4.3.23/thredds-parent-4.3.23.jar
     [exec]              - http://repository-cdn.liferay.com/nexus/content/groups/public/edu/ucar/thredds-parent/4.3.23/thredds-parent-4.3.23.pom
     [exec]              - http://repository-cdn.liferay.com/nexus/content/groups/public/edu/ucar/thredds-parent/4.3.23/thredds-parent-4.3.23.jar
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':libPortal'.
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1054)
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1700(DefaultConfiguration.java:123)
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:1028)
     [exec] 	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:76)
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.iterator(DefaultConfiguration.java:439)
     [exec] 	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileTreeConverter.convertInto(DefaultFileCollectionResolveContext.java:217)
```

despite I also tried committing the JAR and the POM to the .gradle cache, with no luck.

Thank you in advance!

Regards,
Tibor

**Comment by CAustin582** [comment]
Hey guys, I think Unidata removed this version (or at least tried to) from Maven Central. https://search.maven.org/search?q=g:edu.ucar%20AND%20a:netcdf&core=gav

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test

**Comment by lipusz** [comment]
ci:test

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
https://github.com/adolfopa/liferay-portal/pull/899

**Pull request closed without merging**
