### PR TITLE
[TS] LPS-82559 Solr on JBoss/WildFly connecting to SolrCloud throws NoClassDefFoundError for log4j

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-82559](https://issues.liferay.com/browse/LPS-82559)

Hi Tibi,

Please review my changes.

I've tested with both Solr 5.5.5 and Solr 7.2.1 on WildFly 11.

Thanks in advance,
Pisti

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:solr

**Comment by lipusz** [comment]
ci:help

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:solr

**Comment by lipusz** [comment]
ci:test:solr

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by istvansajtos** [comment]
Hi Tibi,

I tested only on WildFly. If the tests keep failing, I will test with Tomcat too.

**Comment by lipusz** [comment]
I'm interested in manual testing: the thing is that line in bnd is there as we expect the underlying system to provide that package.

Fo JBoss, we have `<module name="org.apache.log4j" />` in jboss-deployment-structure.xml since https://issues.liferay.com/browse/LPS-27399, but looks like the package is available at system level in other servers.

So if we remove that exclusion we might create issues on other servers.

**Comment by istvansajtos** [comment]
Thanks for the info, Tibi! I will manual test with Tomcat soon and let you know about the resul,.

**Comment by lipusz** [comment]
https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search-solr/portal-search-solr/build.gradle#L12

https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search-solr7/portal-search-solr7-impl/build.gradle#L14

**Comment by lipusz** [comment]
Looks like they they haven't released yet 3.5 for zookeeper, so we can't use those versions, while 3.4.13 doesn't have the changes.

**Comment by lipusz** [comment]
ci:test:search-solr

**Comment by lipusz** [comment]
Forwarded to Bryan: https://github.com/BryanEngler/liferay-portal/pull/288
Thanks! :+1:

**Pull request closed without merging**
