### PR TITLE
[TS] LPS-86740 Reindex is called twice for MBMessage

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-86740](https://issues.liferay.com/browse/LPS-86740)

Hi Tibi,

Please review my changes.

Thank you,
Pisti

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hi Pisti,

This belongs to the Collaboration team, please send them for review.

Thanks, :+1: 
Tibi

Note: make sure you checked the reason why they added that "doReindex" call to the code in the past in order not to cause regressions.

**Comment by lipusz** [comment]
@istvansajtos Plz also check the failing tests before sending to Collab. Thank you, Pisti!

**Comment by istvansajtos** [comment]
Thanks Tibi! I've fixed the failures and resent to https://github.com/robertoDiaz/liferay-portal/pull/743

**Pull request closed without merging**
