### PR TITLE
[TECHNICAL-SUPPORT] LPS-62030 ldap.import.user.password.enabled=false is not working as expected

### PR DESCRIPTION
**Pull request by NorbertKocsis**
Hi,

Please take a look at this! :)

In commit "LPS-62030 Apply new method" you might notice that whit this change, the scrennName based password will be determined after we check determine what the screenName should be. This is intentional, as it seemed to be another possible bug in case of auto-srceenname. However I didn't check that scenario.

Br,
Norbert

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:retest

**Comment by lipusz** [comment]
Fix for the failures in OLST is on the way: https://github.com/brianchandotcom/liferay-portal/pull/34810
Unrelated.

**Comment by lipusz** [comment]
Started reviewing...

**Comment by lipusz** [comment]
Please, reset the change for the 2nd issue and create a separate ticket. This should ease future tracking.

**Comment by mhan810** [comment]
@lipusz @NorbertKocsis guys, please make sure to send the final to @briangreenwald to test with the changes he's making for another bug fix.  He can send that final to BC together later.

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi @mhan810 

Thank you for the heads up. Is https://issues.liferay.com/browse/LPS-44538 the ticket you were referring to? If so, it's already in BChan's queue: https://github.com/brianchandotcom/liferay-portal/pull/34931

**Comment by lipusz** [comment]
But I'm going to forward this to @briangreenwald anyway

**Comment by mhan810** [comment]
Yep I sent it to BC yesterday

**Comment by lipusz** [comment]
Forwarded to Brian for further review: https://github.com/briangreenwald/liferay-portal/pull/18
Thx!

**Pull request closed without merging**
