### PR TITLE
[TS] LPS-79480 doAsUserId param added to the external URLs when page type is link to URL

### PR DESCRIPTION
**Pull request by rolandpakai**
https://issues.liferay.com/browse/LPS-79480

Please review my changes, and if everything is fine please push it forward.

Thanks, Roland

### CODE REVIEW

**Comment by lipusz** [comment]
Failures seem unrelated to this PR.

**Comment by rolandpakai** [comment]
ci:retest

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Forwarded to https://github.com/topolik/liferay-portal/pull/502.
See my changes: https://github.com/topolik/liferay-portal/pull/502/commits/f8f5a078cb0925e04b8e9023bc52d5a7086532fe

Thanks! :+1:

**Pull request closed without merging**
