### PR TITLE
[TECHNICAL-SUPPORT] LPS-44965 VerifyOracle should reduce columns in 6.1.20 and above if you come from 5.2.9 or from 6.0.5 to 6.1.10

### PR DESCRIPTION
**Pull request by istvansajtos**
**Problem:**
Using the 6.1.10 -> 6.1.20 -> 6.2.10 upgrade path with Oracle DB triggers the error:

_java.sql.SQLException: ORA-01404: ALTER COLUMN will make an index too large_ [Sanitized]_

**Analysis:**
In Oracle the length of VARCHAR2 fields can be specified in BYTE (default) or CHAR. Liferay used BYTE length, which was later multiplied by 4 to have enough space for multi-byte characters. [LPS-25861](https://github.com/liferay/liferay-portal/commit/ada8218acd661611bc75a7676740af3052a9c451#diff-8ff6dc75f0f15bb19692bd7a548e8754) changed this to use original/normalized length specified in CHAR.

When upgrading Liferay, VerifyOracle is responsible to change length spec from BYTE to CHAR and normalize the length (dividing by 4) if necessary:

```
                if (isBetweenBuildNumbers(
                        buildNumber, ReleaseInfo.RELEASE_5_2_9_BUILD_NUMBER,
                        ReleaseInfo.RELEASE_6_0_0_BUILD_NUMBER) ||
                    isBetweenBuildNumbers(
                        buildNumber, ReleaseInfo.RELEASE_6_0_5_BUILD_NUMBER,
                        ReleaseInfo.RELEASE_6_1_20_BUILD_NUMBER)) {

                    // LPS-33903

                    if (!ArrayUtil.contains(
                            _ORIGINAL_DATA_LENGTH_VALUES, dataLength)) {

                        dataLength = dataLength / 4;
                    }
                }

                try {
                    runSQL(
                        "alter table " + tableName + " modify " + columnName +
                            " varchar2(" + dataLength + " char)");
                }
```

ORA-01404 occurs because VerifyOracle changes VARCHAR2 column spec from BYTE to CHAR, but doesn't normalize dataLength. This would produce too big index size.

**Solution:**
The condition must be changed a little bit, so the length division will be executed when upgrading from 6.1.20:

```
                if (isBetweenBuildNumbers(
                        buildNumber, ReleaseInfo.RELEASE_5_2_9_BUILD_NUMBER,
                        ReleaseInfo.RELEASE_6_0_0_BUILD_NUMBER) ||
                    buildNumber >=  ReleaseInfo.RELEASE_6_0_5_BUILD_NUMBER) {
```

We also have to make sure plugin and modularized tables are modified too, that is why I removed _isPortalTableName(tableName)_ check.

Modifying _OracleDB._ORACLE_ array ensures that VARCHAR2 length is specified in CHAR even if the original script defines STRING type. 

**Important note:** On trunk the issue in not reproducible, because the affected indexes doesn't exist there. Even so, I think we should commit this on trunk to unify column length handling in portal, module and plugin tables.                          

Thank you for checking,
Pisti

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by achaparro** [comment]
Hi @istvansajtos,

Taking into account your modifications, could you confirm that we won't reduce the fields during an upgrade from 6.1.20 to 7? This could be dangerous when the fields have the proper lenght in 6.1.20 (most of the cases)

Thanks.

**Comment by lipusz** [comment]
Hi Alberto,

Do you the bandwidth to review Pisti's changes?

@achaparro

**Comment by achaparro** [comment]
Hey @lipusz,

I have already reviewed it a bit and I need first to answer the question I asked to @istvansajtos this morning (please see my question up in this post).

Once this it is solved you could send me the pull request I could review it deeply and move it to developers finally.

Thanks!

**Comment by lipusz** [comment]
Hi Alberto,

Pisti is OoO this week, so he won't be able to answer your question before October 5th.

**Comment by achaparro** [comment]
Then I would need to set the whole environment to perform an upgrade with Oracle, right now I'm really busy for doing that, perhaps I could have time at the end of the week but not sure.

Anyway, since the issue was solved from customer's point of view, perhaps we can wait until next Monday.

Meanwhile, could you send me this pull request?

Thanks!

**Comment by lipusz** [comment]
Hi István,

Now you're back. :-)
Please, check Alberto's comments. Thx!

**Comment by istvansajtos** [comment]
Hi @achaparro,

The condition surrounding the dataLength normalization makes sure that columns with the desired length won't be further divided.
```
                    // LPS-33903

                    if (!ArrayUtil.contains(
                            _ORIGINAL_DATA_LENGTH_VALUES, dataLength)) {

                        dataLength = dataLength / 4;
                    }
```
```
	private static final int[] _ORIGINAL_DATA_LENGTH_VALUES = {
		75, 100, 150, 200, 255, 500, 1000, 1024, 2000, 4000
	};
```

Therefore, if you create a 6120 DB (which comes with proper column lengths out-of-the-box) and then upgrade to 6210, then columns won't be altered. I didn't test this specific upgrade scenario, but this is how it should work based on the source code.

Please let me know if I can help you with anything else.

Thanks!

**Comment by lipusz** [comment]
Thx, István!

@achaparro: I'm forwarding this to you. Please, take care of the further
review and pass it forward to Miguel if you agree.

Thx Guys!

On Mon, Oct 5, 2015 at 12:17 PM, Istvan Sajtos <notifications@github.com>
wrote:

> Hi @achaparro <https://github.com/achaparro>,
>
> The condition surrounding the dataLength normalization makes sure that
> columns with the desired length won't be further divided.
>
>                     // LPS-33903
>
>                     if (!ArrayUtil.contains(
>                             _ORIGINAL_DATA_LENGTH_VALUES, dataLength)) {
>
>                         dataLength = dataLength / 4;
>                     }
>
>     private static final int[] _ORIGINAL_DATA_LENGTH_VALUES = {
>         75, 100, 150, 200, 255, 500, 1000, 1024, 2000, 4000
>     };
>
> Therefore, if you create a 6120 DB (which comes with proper column lengths
> out-of-the-box) and then upgrade to 6210, then columns won't be altered. I
> didn't test this specific upgrade scenario, but this is how it should work
> based on the source code.
>
> Please let me know if I can help you with anything else.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lipusz/liferay-portal/pull/93#issuecomment-145488106>.
>



-- 

*Tibor LIPUSZ*

Senior Software Engineer

Team Lead, Platform TS, EMEA
Search & Security SME, Subscription Services & Release, Global


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

*Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

<http://www.liferay.com>

**Comment by achaparro** [comment]
OK @lipusz, go ahead.

Thanks @istvansajtos

**Comment by lipusz** [comment]
Forwarded to https://github.com/achaparro/liferay-portal/pull/12

**Pull request closed without merging**
