### PR TITLE
LPS-61285

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-61285

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Jorge,

Sorry for the changes, I though it's related to a customer issue, but now I remember to our forum discussion. :-)

**Comment by lipusz** [comment]
I'd like to ask you to restrict the visibility of your comment https://issues.liferay.com/browse/LPS-61285?focusedCommentId=704197&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-704197 to "liferay-staff" at it points to our private SO site.

**Comment by jorgediaz-lr** [comment]
Hi @lipusz, 

I have changed the visibility of that comment.

**Comment by lipusz** [comment]
My problem with this is that after the change, the following code will have no effect:
````java
myCookie.setHttpOnly(false);
````

since it's always be "HttpOnly". And if customer don't want to use, because they're already using 

````properties
    #
    # HTTP only cookies are not supposed to be exposed to client-side scripting
    # code, and may therefore help mitigate certain kinds of cross-site
    # scripting attacks. Input a list of comma delimited cookie names that are
    # not HTTP only.
    #
    cookie.http.only.names.excludes=
````

through the system-ext.properties, they will have to customize the web.xml of the portal which is tough due to our patching mechanism.

What do you think?

**Comment by jorgediaz-lr** [comment]
The configuration at web.xml only applies to session cookie, so customer cookies should not be affected by this modification

**Comment by lipusz** [comment]
Are u sure we won't have cookies we use from JS on client side?

**Comment by jorgediaz-lr** [comment]
- We have some cookies called LFR_SESSION_STATE_XXXX that are created and used only at JS side
 - At server side all cookies generated by Liferay have httpOnly flag (LPS-19107 and LPS-39469) except those that are added to **cookie.http.only.names.excludes=**
 - Cookies generated by liferay are not controlled by web.xml configuration
 - About JSESSIONID session cookie, it is generated with httpOnly=true by default at Tomcat unless you configure web.xml => session-config => cookie-config.http-only = false  . At Jboss is configured by default  with httpOnly=false

After some investigations, I have not found any JS at Liferay using JSESSIONID session cookie.

Nevertheless, If we have any JS trying to access to that session cookie, that cannot work now, (before my changes) at lest at our Tomcat Bundle because tomcat sets httpOnly=true by default in case there is no information at web.xml (current situation)

**Comment by lipusz** [comment]
Thank you, Jorge for the thorough explanation. I appreciate it.

So I reject this pull!😀😀😀

No, I'm just kidding you. I'll forward this to Tomas or Mika tomorrow.

Have a good evening!

Cheers,
Tibi

Sent from mobile
--
Senior Software Engineer
Team Lead, Platform TS, EMEA
Search & Security SME, Subscription Services & Release, Global

**Comment by lipusz** [comment]
One last question: are all of our possible target app servers (configurable from app.server.properties) are supporting Servlet 3.0 by default? We have to make sure the portal can be started properly on all servers after this change.

@jorgediaz-lr

**Comment by jorgediaz-lr** [comment]
Hi @lipusz 

Liferay 7 only runs with application servers that supports Servlet 3.0, see:
  - https://in.liferay.com/web/global.engineering/forums/-/message_boards/message/2527919
  - https://in.liferay.com/web/global.engineering/forums/-/message_boards/message/17781289
  - https://issues.liferay.com/browse/LPS-61283

**Comment by lipusz** [comment]
Forwarded to https://github.com/topolik/liferay-portal/pull/256
:+1:

**Comment by jorgediaz-lr** [comment]
:smiley:  :v:

**Pull request closed without merging**
