### PR TITLE
LPS-87410

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-87410

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:solr

**Comment by lipusz** [comment]
ci:test:search-solr

**Comment by xbrianlee** [comment]
ci:test:bundle

@lipusz This might have to be tested locally. Our SolrCloud test is running into another issue that Linda is looking into [LRQA-50851](https://issues.liferay.com/browse/LRQA-50851).

**Comment by lipusz** [comment]
https://github.com/BryanEngler/liferay-portal/pull/388

**Pull request closed without merging**
