### PR TITLE
[TECHNICAL SUPPORT] LPS-60794 UserGroupLocalServiceUtil.addUserUserGroup and deleteUserUserGroup takes only effect if cached content is cleared

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-60794

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Norbi,

Can you please rebase and push a retest comment? Thx!

**Comment by NorbertKocsis** [comment]
ci:retest

**Comment by NorbertKocsis** [comment]
I've been asked to Bump! this :)

**Comment by lipusz** [comment]
Since the customer got a workaround they're fine with, I'm handling it with a lower priority. I'll process the PR after I finished the training materials for the Thursday/Friday sessions this week.

Thank you for your patience,

Regards,
Tibi

**Comment by lipusz** [comment]
Started reviewing

**Comment by lipusz** [comment]
Sent email to Jorge to verify severity.

**Comment by lipusz** [comment]
While we're waiting for Jorge's response, a simplified fix could be to update the javadoc of the methods and document
- those which can do it gracefully
- those which requires invoking PermissionCache clear + reindex manually.

**Comment by lipusz** [comment]
Hi Norbi,

Can you please modify the pull as we discussed with Jorge in email? Just send me a new pull and I'll close this one.

Thank you and sorry for the delay.

**Comment by arbetts** [comment]
@lipusz @NorbertKocsis 

just wondering if this is still being worked on. I can pick it up if it is backlogged

**Comment by lipusz** [comment]
Hi Andrew,

Sure you can work on it if you have to the time, though you should be aware
of the outcome of the email discussion among Jorge and us.

I've forwarded the thread to you.

Norbi: haven't you been working on the new version, too?

Sent from mobile
--
Sr. Software Engineer, Team Lead
SME of Search & Security
Subscription Services, EMEA

**Comment by arbetts** [comment]
@lipusz 

thanks for forwarding the email thread.

From reading the email thread it looks like this is something that is still in conversation (at least for the permanent solution), and we won't be able to get this in for 7.0. So i'll pick up some other backlogged tasks.

**Pull request closed without merging**
