### PR TITLE
JCords-LPS-112283

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-112283

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf:norebase

**Comment by lipusz** [comment]
ci:test:relevant:norebase

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by lipusz** [comment]
@joshuacords

**Comment by joshuacords** [comment]
Thanks @lipusz, I was meaning to do a self pull - opps.

**Comment by joshuacords** [comment]
ci:close

**Pull request closed without merging**
