### PR TITLE
[TECHNICAL SUPPORT] LPS-60527 Qualifier (SNAPSHOT) is lost from the version's representation

### PR DESCRIPTION
**Pull request by adamtnagy**
https://issues.liferay.com/browse/LPS-60527

Hello Tibor,

I updated the branch and sending this pull request based on the discussion on this one:
https://github.com/lipusz/liferay-portal/pull/98#issuecomment-157691243

The solution saves the qualifier and uses it when toString() is called, but does not use it when comparing two instances.

Thank you,
Ádám

### CODE REVIEW

**Comment by lipusz** [comment]
Please, do not create a new constant for StringPool.BLANK. It's already final static. :+1:

**Comment by adamnagy** [comment]
Sorry, I fixed it up.

**Comment by lipusz** [comment]
Started reviewing...

**Comment by lipusz** [comment]
Hi Ádám,

You can release it as an SDH. Please, create a BPR for 62x. I already have created https://issues.liferay.com/browse/LPE-14517 for this LPS.

**Comment by lipusz** [comment]
Forwarded to https://github.com/mhan810/liferay-portal/pull/822

**Pull request closed without merging**
