### PR TITLE
[TS] LPS-75590 Fix NullPointerException that occurs when deploying a plugin that uses the Configuration API

### PR DESCRIPTION
**Pull request by peterpetrekanics**
Hi Tibi,

Please review my fix for this LPS:
[LPS-75590](https://issues.liferay.com/browse/LPS-75590)

Thank you,
Peter

### CODE REVIEW

**Comment by peterpetrekanics** [comment]
ci:reopen

**Comment by peterpetrekanics** [comment]
ci:retest

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Forwarded to https://github.com/izaera/liferay-portal/pull/24.
See my changes: https://github.com/izaera/liferay-portal/pull/24/commits/175ac14d163389eb0eb1fe480fb68ec972e83c26
* We avoid chaining according to our coding style: `type.getName().equals(Meta.OCD.class.getName()`
* If you search for how we handle the various exceptions that can be thrown when playing with reflection you can see that we catch `ReflectiveOperationException`
* We don't need to iterate over all the methods since we know what method we are looking for: `annotationType.getMethod("id")`

:+1:

**Pull request closed without merging**
