### PR TITLE
[TS] LPS-77366 When editing the Permissions for a resource like a document or web article, then the Permission window (edit_permission.jsp) shows roles that should not be listed

### PR DESCRIPTION
**Pull request by peterpetrekanics**
Hi Tibi,

Please review my fix, I have created a new portal property as discussed on the related PTR:
https://issues.liferay.com/browse/PTR-267

Setting the property to true will enforce the new behavior which means that the TestRole and TestSiteRole will not be displayed.
Leaving the property on the default value (false) will maintain the old behavior and show all roles.

Link to the LPS ticket:
[LPS-77366](https://issues.liferay.com/browse/LPS-77366)

Manual testing shows that the fix correctly resolves the issue.
In case this modification is accepted I will update the LPS with a "QA/Solution Notes" as mentioned in:
https://grow.liferay.com/share/What+Support+Can+Do+to+Improve+Documentation

Thank you,
Peter

### CODE REVIEW

**Comment by peterpetrekanics** [comment]
ci:test

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
Hi Petya,

Please check the SF errors and fix them in the pull.

Thanks,
Tibi

@peterpetrekanics

**Comment by lipusz** [comment]
Also, I'd consult with the User and System Management SME first to see if your approach is good. My concern is not really about having the ability to control this behavior, but the way you chose to control it: as of 7.0 we don't introduce new portal properties unless it's really-really necessary and can't be avoided.

The recommended approach is to use the OSGi Config Admin (= System Settings).

Can you please consult with him and update your code accordingly?

Since the issue is not in the permissions framework, I suggest to send to review to the SME.

Regards,
Tibi

**Pull request closed without merging**
