### PR TITLE
[TS] LPS-67650

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi Tibor,

This pull comes from [here](https://github.com/lipusz/liferay-portal/pull/141). This was my original idea, and we are modifying only Solr module, because this case is only related to Solr, but maybe it is not the smartest solution because I'm recovering old code that was removed in [LPS-50968](https://issues.liferay.com/browse/LPS-50968).

As you know, you can find further information in [LPS-67650](https://issues.liferay.com/browse/LPS-67560), the first pull I sent you and the [forum thread](https://in.liferay.com/web/support/forums/-/message_boards/message/24217250) where we discussed it.

Thanks,

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Antonio,

Please remember when sending a PR for review to also update the related JIRA ticet and place it to "In Review", link the pr and assign to the reviewer.

I did it for you know. ;-)

Fyi: if you're working on TS, you can find more about our processes [here](https://grow.liferay.com/group/guest/people/-/wiki/Grow/TSE+Knowledge+Base).

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi @antonio-ortega 

We need a solution that works with all kind of queries, not just with TermQuery. Right now the only way I can think of is to apply the "escape" logic to all *QueryTranslator-s where we pass in the field name.

It's a bit ugly, so if you have a better idea please go ahead and send me. ;-)

**Comment by marianoalvarosaiz** [comment]
Hi @lipusz,
 we agree that the final solution should take into account every possible type of query when it's composed out of terms. Unfortunately we're very busy right now and we need to provide quickly a fix to our customer, so we will generate it with this code, and left the LPS open so that if we have time, or someone else wants to take it, a general solution can be created and merged into master.
Thanks a lot for your time.

cc @antonio-ortega @achaparro

**Pull request closed without merging**
