### PR TITLE
LPS-70054 Preventing Liferay from throwing NPE when LDAP Server is configured with wrong attributes

### PR DESCRIPTION
**Pull request by cleydyr**
https://issues.liferay.com/browse/LPS-70054

### CODE REVIEW

**Comment by lipusz** [comment]
Please rebase and hit ci retest. Thx!

**Comment by cleydyr** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
https://github.com/mhan810/liferay-portal/pull/1310.
Thx! :+1:

**Pull request closed without merging**
