### PR TITLE
[TECHNICAL SUPPORT] LPS-70094

### PR DESCRIPTION
**Pull request by amadeafejes**
https://issues.liferay.com/browse/LPS-70094

### CODE REVIEW

**Comment by amadeafejes** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by amadeafejes** [comment]
ci:retest

**Comment by amadeafejes** [comment]
ci:retest

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/3714
Thanks! :+1:

**Pull request closed without merging**
