### PR TITLE
[TECHNICAL SUPPORT] LPS-50886 Race condition during parallel rendering in IconMenuTag

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-50886

### CODE REVIEW

**Comment by lipusz** [comment]
Please, rebase, push & re-test.

**Comment by NorbertKocsis** [comment]
ci:retest

**Comment by lipusz** [comment]
Started reviewing...

**Comment by lipusz** [comment]
Please rebase and re-test.

**Comment by lipusz** [comment]
https://github.com/Preston-Crary/liferay-portal/pull/106

**Pull request closed without merging**
