### PR TITLE
[TECHNICAL SUPPORT] LPS-64261 Performance issue because of missing index

### PR DESCRIPTION
**Pull request by vilmospapp**
Hi @lipusz 

I've rebased the code from https://github.com/lipusz/liferay-portal/pull/117 and now sending it for you to review.

### CODE REVIEW

**Comment by lipusz** [comment]
Please, take a look at this: https://loop.liferay.com/home/-/loop/feed/1402203

Related to semantic versioning.

**Comment by lipusz** [comment]
Also related to kernel changes: https://loop.liferay.com/home/-/loop/feed/1331196

**Comment by lipusz** [comment]
ci:retest

**Comment by vilmospapp** [comment]
Hi Tibi,

I see this is the way we should deal with it: https://loop.liferay.com/web/guest/home/-/loop/feed/1409977 but I have no slack account. As an SME, I think probably you have, can you please drop in this issue there to ask for how to resolve the semantic versioning issue?

**Comment by lipusz** [comment]
I expect more information coming from Ray, so stay tuned and follow "Engineering". I'll also keep one of my eyes on it as well as following the conversation on Slack.

**Comment by lipusz** [comment]
According to Ray:
>You must increment the version of the specified packages. If you enable semantic versioning report locally, it will do this work for you.

**Comment by lipusz** [comment]
ci:retest

**Pull request closed without merging**
