### PR TITLE
LPS-104693

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-104693

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:solr

**Comment by lipusz** [comment]
ci:test:solr

**Comment by lipusz** [comment]
ci:test:solr:norebase

**Comment by lipusz** [comment]
ci:test:solr

**Comment by joshchong** [comment]
ci:test:search-solr

**Comment by joshchong** [comment]
@lipusz the `ci:test:search-solr` look good to me! The only unique failure is the one in `functional-upgrade-tomcat90-mysql57-jdk8/9`, which looks like it was caused by a network issue. All other failures are known and unrelated.

**Comment by lipusz** [comment]
ci:test:sf:norebase

**Comment by lipusz** [comment]
https://github.com/BryanEngler/liferay-portal/pull/447

**Pull request closed without merging**
