### PR TITLE
[TS] LPS-78119 Web Content fields behave inconsistently when searched

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-78119](https://issues.liferay.com/browse/LPS-78119)

Hi Tibi,

I'm sending the [changes you requested](https://github.com/lipusz/liferay-portal/pull/221#issuecomment-392120369) on #221

Thank you,
Pisti

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Hi Pisti, @istvansajtos 

Is there a special reason why you are not using `com.liferay.portal.kernel.search.SearchContext.getGroupIds()` instead of `(Long)searchContext.getAttribute("groupId");`?

**Comment by istvansajtos** [comment]
Hi Tibi,

There is no specific reason, it is just a mistake. I update my branch to replace those calls.

**Comment by lipusz** [comment]
Hi Pisti, @istvansajtos 

:heavy_plus_sign: `JournalArticleIndexer.doGetSummary` also needs to be updated to get the "snippet" from the right fields.

**Comment by lipusz** [comment]
Looks like there is a merge conflict. Can you please do the rebasing, too?

**Comment by istvansajtos** [comment]
Hi Tibi, @lipusz

Of course. This is on my to-do list for today.

**Comment by lipusz** [comment]
Closing as per our discussion with the following action:
* Send to Euadaldo in the WCM team with proper explanation about the changes and "spec" you followed to create the fix
* Tell him that this may be a behavioral change
* Decide with him if it's a `7.1-must` or `7.1-should`
* CC the WCM SME too, Daniel Couso

Thanks! :+1:

**Pull request closed without merging**
