### PR TITLE
[TECHNICAL-SUPPORT] LPS-58567 Redirect to user's default layout with auth.forward.by.last.path=false

### PR DESCRIPTION
**Pull request by istvansajtos**
https://issues.liferay.com/browse/LPS-58567

**Problem**
The description of _auth.forward.by.last.path_ contains the following:

> ... If set to false, users will be forwarded to their default layout page.

What actually happens is that users are forwarded to the homepage of the site configured in _virtual.hosts.default.site.name_ property at login. After clearing the value of this property (which is "Guest" by default), users are redirected to their default layout page as expected.

**Analysis**
The logic to determine the layout where user is forwarded is encapsulated by _ServicePreAction.getDefaultViewableLayoutComposite()_. (Originally it was in _ServicePreAction.getDefaultLayout()_.) Now the logic attempts to determine the layout following the below order:
1. virtual.hosts.default.site.name property
2. user's personal layouts (if logged in)
3. user's sites (if logged in)
4. Guest site. 

This is not in accordance with the description of auth.forward.by.last.path property. This issue was fixed once by [LPS-13464](https://issues.liferay.com/browse/LPS-13464), but [LPS-49338](https://issues.liferay.com/browse/LPS-49338?focusedCommentId=497476&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-497476) reverted it saying that virtual host should take precedence over personal layout and user's sites. Unfortunately this reintroduced the problem.

**Solution**
According to the description of auth.forward.by.last.path user's personal layout should take precedence over virtual host. I am changing the order as follows fix the issue:
1. user's personal layouts (if logged in)
2. virtual.hosts.default.site.name property
3. user's sites (if logged in)
4. Guest site. 

Thanks for checking!
Pisti

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:retest

**Comment by istvansajtos** [comment]
ci:retest

**Comment by istvansajtos** [comment]
I am going to check why ServicePreActionTest.testInitThemeDisplayPlidDefaultUserSitesLayoutComposite fails.

**Comment by lipusz** [comment]
Ok, please resend when it's done.

On Thu, Sep 17, 2015 at 1:24 PM, Istvan Sajtos <notifications@github.com>
wrote:

> I am going to check why
> ServicePreActionTest.testInitThemeDisplayPlidDefaultUserSitesLayoutComposite
> fails.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lipusz/liferay-portal/pull/90#issuecomment-141048344>.
>



-- 

*Tibor LIPUSZ*

Senior Software Engineer

Team Lead, Platform TS, EMEA
Security SME, Subscription Services & Release, Global


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

*Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

<http://www.liferay.com>

**Pull request closed without merging**
