### PR TITLE
[TECHNICAL SUPPORT] LPS-60527 SNAPSHOTs of a version are not considered lower than the actual version, and the "SNAPSHOT" String is lost when deployed

### PR DESCRIPTION
**Pull request by adamtnagy**
https://issues.liferay.com/browse/LPS-60527

Hello Tibor,

The issue was that on the Control Panel an administrator could not see if a plugin was a snapshot or not. By saving SNAPSHOT to the Version object I needed to update the compareTo process to be able to distinguish between the final version and a snapshot one.

For more information please review the LPS.

Thank you,
Ádám

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Ádám,

Please, remove "LPS-57182" from your commit messages and use the new LPS number as the old one is already released in a fix pack, so we cannot push additional commits under that ticket.

Thx!

**Comment by adamnagy** [comment]
I knew I missed something to update!

:-(

**Comment by adamnagy** [comment]
I re-pushed. Sorry for the inconvenience

**Comment by lipusz** [comment]
Hi @adamnagy 

````
1 Test Failed.

    SourceFormatterTest.testSourceFormatter
````
means there are SF issues in your pull. Please, double-check.

**Comment by adamnagy** [comment]
Hi,
Sorry, again, I found the issue. Re-pushed.

**Comment by adamnagy** [comment]
ci:retest

**Comment by adamnagy** [comment]
ci:retest

**Comment by adamnagy** [comment]
ci:retest

**Comment by adamnagy** [comment]
Hi Tibor,

I rebased this branch, and tested on my side:
https://github.com/adamnagy/liferay-portal/pull/3

This test should be successful.
Thanks,
Ádám

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Ádám,

Here's the summary of our talk:
1- SNAPHOT is a special qualifier used mainly in MAVEN projects and is usually related to continuous integration. Here's a good article: https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm

2- Using alpha-numerical characters are allowed, though, discouraged by https://www.liferay.com/documentation/liferay-portal/6.2/development/-/ai/marketplace-basics-liferay-portal-6-2-dev-guide-11-en ("Version" section).
Without a hierarchy, neither the portal nor humans can decide the relationship between two versions.

3- There can be other qualifiers, e.f. NIGHTLY, BETA etc. The proposed solution doesn't preserve such qualifiers.

What I'd do is to keep the qualifiers in when constructing the toString from a Version, but doesn't use it when comparing versions. I am not aware of any documentation saying Liferay is tied to the MAVEN versioning, so the comparison should not deal with these special cases in my opinion.

In addition, please do not create new constants to store constants from StringPool or CharrPool. They're already declared as "static final".

Please, resend.

Thx,
Tibi

**Pull request closed without merging**
