### PR TITLE
[TS] LPS-73641

### PR DESCRIPTION
**Pull request by ugurcancetin**
Hi Tibi,

As I have mentioned, I couldn't resolve the test fails. 
If possible, I would like to get some help from you to resolve when you have time.

https://issues.liferay.com/browse/LPS-73641

Thanks,
Ugurcan

### CODE REVIEW

**Comment by ugurcancetin** [comment]
ci:retest

**Comment by lipusz** [comment]
Because of the removal of lowercase, StringUtil should not be imported in the affected test classes. This causes the last failure. Please fix it and retest.

**Comment by ugurcancetin** [comment]
ci:retest

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
:warning:  After the changes, the assets created by the "Test Test" user cannot be found no matter if I search for "test" or "Test" so you will need to find a different solution.

If you test it before your changes (e.g. on http://master.liferay.org.es) you will see the results.

Maybe we could use a separate field to store the User's name in case of User objects, but nevertheless, you should investigate it further.

**Pull request closed without merging**
