### PR TITLE
[TECHNICAL-SUPPORT] LPS-57200 Document from other Site is not visible from Scoped Asset Publisher

### PR DESCRIPTION
**Pull request by zsolah**
Hi,

Please review.

Thanks.

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Zsolt,

Are you sure you wanted to send this to me? It's related to WCM and AP.

**Comment by zsolah** [comment]
Hello,
yes since the change is in ServicePreAction.java .

**Comment by zsolah** [comment]
I have previously sent this to WEM , but moltam89 has requested me to send it to the platform team.
https://github.com/moltam89/liferay-portal/pull/350#issuecomment-144388793

**Comment by lipusz** [comment]
Started reviewing...

**Comment by lipusz** [comment]
Hi Zsolt,

With the steps you provided, the newly created user cannot cannot see the AP on SiteB's page.
In addition, despite the changes you made are in the ServicePreAction, it's heavily related to Sites & scopes, so you should send to Eduardo or Julio I think.

Thx,
Tibi

**Pull request closed without merging**
