### PR TITLE
[TS] LPS-78119 Web Content fields behave inconsistently when searched

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-78119](https://issues.liferay.com/browse/LPS-78119)

Hi Tibi,

This is the continuation of https://github.com/lipusz/liferay-portal/pull/218 which I have rebased as per your request.

Thank you,
Pisti

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test

**Comment by istvansajtos** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Pisti,

As this issue originates from a long-discussion, can you please double-check if the description of the LPS is aligned with the intent of this PR and covers what you customer reported?

Thanks,
Tibi

@istvansajtos

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
ci:retest

**Comment by istvansajtos** [comment]
Hi Tibi,

I have updated the LPS description to make it more clear where this issue originates from and what expected outcome was determined by the product team.

Regarding the customer's expectation, the change seems to be in line with that.

Thanks,
Pisti

@lipusz

**Comment by istvansajtos** [comment]
ci:reopen

**Comment by lipusz** [comment]
I can't reopen it either... Can u please resend?

**Comment by istvansajtos** [comment]
New PR is available here: https://github.com/lipusz/liferay-portal/pull/221

Sorry for the inconvenience.

**Pull request closed without merging**
