### PR TITLE
[TECHNICAL-SUPPORT] LPS-61779 Add test for #102

### PR DESCRIPTION
**Pull request by djavorszky**
Hi Tibi,

I've added tests for the code change. I also cherry picked your SF and Drew's commit and rebased it to master.

Best,
Dani

### CODE REVIEW

**Comment by lipusz** [comment]
Commit message? :-)

**Comment by djavorszky** [comment]
Oooops :-) Sorry, amended.

**Comment by lipusz** [comment]
Please, rebase to drewbrokke's LPS-61779 branch

**Comment by djavorszky** [comment]
I think I managed to do so, please check.

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
There is a related SF error:
````
java.lang.Exception: Incorrect tab or line break: ../../../portal-impl/test/integration/com/liferay/portal/service/OrganizationLocalServiceTest.java 485
````

Please correct & fixup.

**Comment by djavorszky** [comment]
ci:retest

**Comment by lipusz** [comment]
https://github.com/JorgeFerrer/liferay-portal/pull/633

Thx!

**Pull request closed without merging**
