### PR TITLE
[TECHNICAL-SUPPORT] LPS-73886 URL encoding issues on language change

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-73886](https://issues.liferay.com/browse/LPS-73886)

Hi Tibi,

Please review the changes. It won't be difficult. :)

Thanks,
Pisti

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:retest

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Hi Pisti,

I'm not sure if this is the right place to encode the URL, but I need to test my idea. I try to proceed with this today.

**Comment by lipusz** [comment]
Hi Pisti,

Can you please rebase it and hit retest? @istvansajtos

**Comment by istvansajtos** [comment]
ci:retest

**Comment by istvansajtos** [comment]
Done. :)

**Comment by lipusz** [comment]
Forwarded to https://github.com/ealonso/liferay-portal/pull/1074.
Thanks!: :+1:

**Comment by lipusz** [comment]
Please do the backport for 70x after it's merged. @istvansajtos

**Comment by lipusz** [comment]
ci:stop

**Pull request closed without merging**
