### PR TITLE
[TS] LPS-77597 Update apache-log4j-extras version -- 1.2.17

### PR DESCRIPTION
**Pull request by csababotos**
https://issues.liferay.com/browse/LPS-77597

Hi Tibi,

please review changes.

Regards,
Csaba

### CODE REVIEW

**Comment by lipusz** [comment]
@csababotos Please hit ci:test to trigger testing as it's indicated by the CI comment.

**Comment by csababotos** [comment]
ci:test

**Comment by csababotos** [comment]
ci:help

**Comment by csababotos** [comment]
ci:retest

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Forwarded to https://github.com/shuyangzhou/liferay-portal/pull/5643.
Thanks! 👍 

Please take care of the backpors after it's merge to master.

**Comment by lipusz** [comment]
ci:stop

**Pull request closed without merging**
