### PR TITLE
[TECHNICAL-SUPPORT] LPS-26811 Error in log when creating url with liferay-portlet:renderU…

### PR DESCRIPTION
**Pull request by peterborkuti**
…RL and target portlet does not have current portletMode

Hi,

Please, review it.

There is a test portlet here:
https://issues.liferay.com/browse/LPS-26811

There is a forum thread about this fix, you can find it on the LPP:
https://issues.liferay.com/browse/LPP-19723

Thank you in advance
Péter

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Péter,

Thank you for working on this. I'd like to ask you to also update the internal forum thread with the information about this LPS just for the record. :+1:

**Comment by peterborkuti** [comment]
Your welcome.
I mentioned this LPS in the first comment.

**Comment by lipusz** [comment]
Hi Péter,

I just wanted to let you know that I've to work on the 7.0 training
materials for Search this week so my review might be delayed for this pull.

Nevertheless, I'll have a quick look over it and give you a green light if
it looks OK so you can build an SDH.

Thank you for your consideration.

Sent from mobile
--
Sr. Software Engineer, Team Lead
SME of Search & Security
Subscription Services, EMEA

**Comment by peterborkuti** [comment]
OK. If you want, I can send it to Andrew, because this code is based  on his idea, I just extend it with the first if.

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Started reviewing

**Comment by lipusz** [comment]
Hi @peterborkuti 

Did you rebase it to latest master today?

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
https://github.com/arbetts/liferay-portal/pull/41

**Pull request closed without merging**
