### PR TITLE
[TECHNICAL-SUPPORT] LPS-62480 Do not call flushInits without actual deployment

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-62480](https://issues.liferay.com/browse/LPS-62480)

**Problem:**
Using PortalDelegateServlet can cause deployment/initialization problems. The cause is that we call flushInits even if the plugin have been put into the deployment queue due to missing dependencies. Through flushInits the initialization of the servlet defined in PortalDelegateServlet's servlet-class init-param will be started attempting to access object prepared only later in the context initialization false.

Specifically, in [LPS-62480](https://issues.liferay.com/browse/LPS-62480) the issue is the following: After startup the portlets are deployed and their servlets are initialized. PortalDelegateServlet is registered as a portal lifecycle. Although the plugin cannot be deployed in the first round due to missing dependencies, flushInits is still invoked taking care of registered portal lifecycles. PortalDelegateServlet - as one of them - will therefore initialize the servlet its servlet-class init-param refers to, in our case Spring's DispatcherServlet. At a certain point this wants to initialize a WebApplicationContext object, but fails as the object it needs would be prepared by contextInitialized method, but the deployment haven't gotten to this phase yet. (As a result DispatcherServlet will be unable to match the URL paths with the mapped controllers.)

**Solution:**
Doesn't call flushInits if the plugin is queued for later deployment.

**Note:** As Tomcat's FAQ says: "There is no expected startup order." (http://wiki.apache.org/tomcat/FAQ/Miscellaneous#Q27) Due to this fact it may be possible that you won't be able to reproduce the issue with the steps on the LPS ticket.

### CODE REVIEW

**Comment by lipusz** [comment]
>Deploy the attached SpringMVCTest web plugin that depends on

No attachment on the ticket.

**Comment by istvansajtos** [comment]
Regarding the test results, I saw those failures on master even without my modifications. I believe we can ignore those.

**Comment by istvansajtos** [comment]
I have attached the missing test plugin to the ticket.

**Comment by lipusz** [comment]
Started reviewing...

**Comment by lipusz** [comment]
Hi Pisti,

Please, move the last paragraph ("some insights") of the description on the ticket to a comment. Simply give a title to the comment something like "Technical background" or whatever.

**Comment by lipusz** [comment]
The plugin-package,properties of the attached spring test portlet doesn't contain the marketplace-portlet as a required deployment context.
In addition, marketplace is now an OSGi app in master, so the reproduction steps don't apply completely.

I'd suggest to use the mail-portlet instead and update your steps (and the descriptor file) to be consistent across portal versions this way making QA's work easier.

**Comment by lipusz** [comment]
OK, I updated.

**Comment by lipusz** [comment]
Please, delete the old attachments.

Actually, with having this
````properties
required-deployment-contexts=mail-portlet,web-form-portlet
````

I can't reproduce the issue. I'm doing a double check in 6.2.x

**Comment by lipusz** [comment]
Ah, I totally forgot that the marketplace dependency is defined in a different way, so you don't need to set it explicitly. :-)

**Comment by lipusz** [comment]
Hi Pisti,

Maybe it's because my Sunday, but this condition
````java
					if (_dependentHotDeployEvents.contains(dependentEvent)) {
						dependentEvent.flushInits();
					}
````

doesn't fix the issue: if SpringMVC Test portlet cannot be deployed due to missing dependencies, it'll still present in the _dependentHodDeployEvents list, but you still invoke the flushInits.

Didn't you want to negate the condition? :-)

@istvansajtos

**Comment by istvansajtos** [comment]
Hi Tibi,

You are right, the condition must be negated. I don't understand how it passed my manual test in this form. I will double-check it and resend if necessary.

Thank you,
Pisti

**Comment by lipusz** [comment]
Ok, please resend.

**Pull request closed without merging**
