### PR TITLE
[TECHNICAL SUPPORT] LPS-60527 + LPS-62383 Version qualifier (e.g. SNAPSHOT) is not displayed in the App Manager + Consider -SNAPSHOT versions lower that the actual version

### PR DESCRIPTION
**Pull request by adamtnagy**
https://issues.liferay.com/browse/LPS-60527
https://issues.liferay.com/browse/LPS-62383

Hello Tibor,

LPS-60527 Is a regression fix for the issue where the SNAPSHOT qualifier is lost in the String representation of a Version.

In this I only put back the qualifier to the toString() method and made sure to ignore it when comparing versions. -> No behavior change when backporting.

---

LPS-62383 is a new feature where we consider the SNAPSHOT version a lower version than the actual one: 1.2.3-SNAPSHOT is smaller than 1.2.3.

Based on the discussion here: https://github.com/JorgeFerrer/liferay-portal/pull/617#issuecomment-171648083

I tried to gather and organize all the information found so far on the ticket descriptions. I think it is worth reading.

Thank you,
Ádám

### CODE REVIEW

**Comment by adamnagy** [comment]
Hi,

I think these failures are not related, I have seen these several times before.

Ádám

**Comment by lipusz** [comment]
Yes, you're right, the fix is on the way: https://github.com/brianchandotcom/liferay-portal/pull/34810

**Comment by lipusz** [comment]
Hi,

Please rebase & push.
Then comment "ci:retest"

**Comment by adamnagy** [comment]
Rebased

**Comment by adamnagy** [comment]
ci:retest

**Comment by lipusz** [comment]
Danke.

**Comment by lipusz** [comment]
Hi,

Please, send it to @abetts, I don't have time to review this.

Thx,
Tibi

**Comment by lipusz** [comment]
Sorry... :-/

**Comment by lipusz** [comment]
For future reference: https://github.com/arbetts/liferay-portal/pull/39

**Pull request closed without merging**
