### PR TITLE
[TS]  LPS-92393 manage single value dispatcherProperty in InvokerFilterHelper

### PR DESCRIPTION
**Pull request by csababotos**
https://issues.liferay.com/browse/LPS-92393

Hi Tibi,

please, check this request.

Regards,
Csaba

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hey Csaba,

Looks like there are some SF errors in the changes. Please, run `ant format-source-current-branch ` from portal-impl and make/review the printed changes and commit them. Then, fixup into the sf changes into your "original" commit.

Thank you! @csababotos

**Comment by csababotos** [comment]
Hi Tibi,

I'm going on with SF.

Thanks,
Csaba

@lipusz

**Comment by csababotos** [comment]
Hi Tibi,

applied SF.

Regards,
Csaba

**Comment by csababotos** [comment]
ci:test

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
`ci:test` is heavy, running `ci:test:sf` is enough to test SF

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
ci:test:relevant:norebase

**Comment by lipusz** [comment]
Testing review changes here: https://github.com/lipusz/liferay-portal/pull/262

**Comment by lipusz** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/7564

**Pull request closed without merging**
