### PR TITLE
[TS] LPS-88338

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @lipusz ,

Can you help review this unfinished ticket?
The ticket has to do with login and is marked as 7.3-must.

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hey Eric,

Can you please send it to liferay-appsec?  
https://grow.liferay.com/excellence/How+to+send+Pull+Request+to+the+Application+Security+Team+liferay-appsec

Thanks!

**Comment by lipusz** [comment]
https://github.com/liferay-appsec/liferay-portal/pull/101

**Pull request closed without merging**
