### PR TITLE
[TECHNICAL SUPPORT] LPS-69480

### PR DESCRIPTION
**Pull request by amadeafejes**
https://issues.liferay.com/browse/LPS-69480

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Ami,

If you take a look at the test failures, you'll see that your changes causing SF errors in GroupFinderTest: https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/21167/testReport/com.liferay.source.formatter/SourceFormatterTest/testSourceFormatter/

Can you please
- fix it
- fixup the changes into your last commit
- update your branch in your origin by pushing it with ```--force```
- then send ci : retest

Thanks! :+1:

**Comment by amadeafejes** [comment]
ci:retest

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Forwarded to Brian: https://github.com/brianchandotcom/liferay-portal/pull/45548
See my changes: https://github.com/brianchandotcom/liferay-portal/pull/45548/commits/8395deb27c2e41bd632bc8ee41d280aedab09803

**Comment by lipusz** [comment]
Thanks! :+1:

**Pull request closed without merging**
