### PR TITLE
[TS] LPS-71456

### PR DESCRIPTION
**Pull request by ugurcancetin**
https://issues.liferay.com/browse/LPS-71456

Hi @lipusz ,

I have tested it on both master and also ee-7.0.x . I uploaded the photo from LDAP as well with mapped portrait. Everything worked properly. 

Thanks,
Ugurcan

### CODE REVIEW

**Comment by ugurcancetin** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Forwarded to https://github.com/mhan810/liferay-portal/pull/1319.
Thanks! :+1:

**Comment by lipusz** [comment]
Please send the backport for 70x once it's merged to master.

**Pull request closed without merging**
