### PR TITLE
[TS] LPS-71001

### PR DESCRIPTION
**Pull request by amadeafejes**
https://issues.liferay.com/browse/LPS-71001

### CODE REVIEW

**Comment by amadeafejes** [comment]
ci:retest

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Testing after restructuring and rebase: https://github.com/lipusz/liferay-portal/pull/204

**Comment by lipusz** [comment]
https://github.com/lipusz/liferay-portal/pull/209

**Pull request closed without merging**
