### PR TITLE
[TECHNICAL-SUPPORT] LPS-65203

### PR DESCRIPTION
**Pull request by eperezg**
https://issues.liferay.com/browse/LPS-65203

Hi Tibor, Could you please take a look alt this? Regards, Eduardo

### CODE REVIEW

**Comment by lipusz** [comment]
Ticket? :-)

**Comment by lipusz** [comment]
Hi Eduardo,

You need to track the process on the ticket, so when you send a pull, you need to click on "Review Request" on the LPS and fill out the form accordingly + assign the ticket to the reviewer. :+1:

**Comment by eperezg** [comment]
Thanks Tibor.

**Comment by lipusz** [comment]
:smile:

**Comment by lipusz** [comment]
Hi Eduardo,

Please, double-check that your fix doesn't re-introduce the issue fixed in the causing LPS.

**Comment by eperezg** [comment]
Hi Tibor,

You are right, I didn't test this!

I've just reproduced the issue, so I'm going to add a new commit in order to keep compatibility with that LPS.

Thank you for your help.

Eduardo

**Comment by eperezg** [comment]
Hi Tibor,

Pull updated.

Thanks

**Comment by lipusz** [comment]
Started reviewing...

**Comment by eperezg** [comment]
Hi Tibor,

Is there something I can do?
It seems the tests have failed. Can we rerun them?

Regards,
Eduardo

**Comment by lipusz** [comment]
Test failures look unrelated. :+1:

**Comment by lipusz** [comment]
Hi Eduardo,

One question: why do you added further conditions:
````java
if (Validator.isNotNull(realUser) && realUser.isDefaultUser() && ...
````

checking
````java
!company.isStrangers
````
(as before) should be enough, shouldn't?

@eperezg

**Comment by lipusz** [comment]
I've figured this out in the meantime.

**Comment by lipusz** [comment]
Forwarded to Tomas: https://github.com/topolik/liferay-portal/pull/333

**Comment by eperezg** [comment]
Hi Tibor,

First fo all, thanks for all your help on this issue.

Secondly, I'm not sure if this action could be fired by a registered user in order to register another user.

Regards,
Eduardo

**Pull request closed without merging**
