### PR TITLE
LPS-69762 system packages

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-69762

### CODE REVIEW

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
system.packages.extra.mf

**Comment by lipusz** [comment]
ci:retest

**Comment by stian-sigvartsen** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
https://github.com/lipusz/liferay-portal/pull/161

**Pull request closed without merging**
