### PR TITLE
LPS-124213

### PR DESCRIPTION
**Pull request by lipusz**

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:workflow

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
ci:test:workflow

**Comment by joshchong** [comment]
Hey @lipusz, the failures above are a red herring. there was a regression introduced to master [LPS-124357](https://issues.liferay.com/browse/LPS-124357) causing all of the workflow metric tests to fail, right when we needed them the most :sweat_smile:. I'll monitor that ticket and rerun the tests on master once the issue has been resolved.

Though I was able to analyze the changes on 7.3.x and discovered additional relevant issues which I posted about in the ticket: https://issues.liferay.com/browse/LPS-124213?focusedCommentId=2329081&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2329081

**Comment by lipusz** [comment]
ci:test:workflow

**Comment by lipusz** [comment]
ci:help

**Pull request closed without merging**
