### PR TITLE
[TECHNICAL-SUPPORT] LPS-61779 OrganizationLocalService.hasUserOrganization throws NPE if both parameters are true

### PR DESCRIPTION
**Pull request by djavorszky**
https://issues.liferay.com/browse/LPS-61779

Hi Tibi,

OrganizationLocalService.hasUserOrganization threw a NullPointerException if both inheritSuborganizations and includeSpecifiedOrganization parameters were true, and the organization's parent was the default organization id. In addition, there was a scenario in which the logic returned wrong result. Consider the following scenario:

Organization A has two sub organization: Organization B and C. The user is the member of Organization C.

If I run the original code on Organization B with both parameters set to true, the method would check the organization's parent (Org A). Since sub-organizations are also checked, the method returned true because the user in question was the member of Organization C. This is wrong, as I wanted to know if the user is the member of Organization B or any of its sub-organizations.

I also added a check on the organizationsTree object. If it's empty for some reason (includeSpecifiedOrganization is false and there are no sub-organizations), then we should not query the database (or cache) with an empty list but rather return false immediately.

Best,
Dani

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Dani,

Please, add yourself to the Liferay organization on GitHub: https://help.github.com/articles/publicizing-or-hiding-organization-membership/

Then, post a comment with this content: ci:retest

**Comment by djavorszky** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Started reviewing...

**Comment by lipusz** [comment]
Forwarded to Hugo: https://github.com/hhuijser/liferay-portal/pull/2598
Thx! :+1:

**Pull request closed without merging**
