### PR TITLE
[TS] LPS-85702 Add test

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-85702](https://issues.liferay.com/browse/LPS-85702)

Hi Tibi,

These are the tests you requested. Please let me know if you see any improvement point.

FYI, I found a way to keep the test method failures isolated from other test methods. So further modifications in the test class were not required.

Thank you,
Pisti

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
c:test:search

**Comment by istvansajtos** [comment]
c:test:search

**Comment by istvansajtos** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
Forwarded to https://github.com/mhan810/liferay-portal/pull/1446 under https://issues.liferay.com/browse/LPS-86663 as LPS-85702 has already been scheduled into the next fix packs.

See my changes: https://github.com/mhan810/liferay-portal/pull/1446/commits/25abbf66ab01072baab7c55a16339b6ca9300eec

Thanks! :+1:

**Pull request closed without merging**
