### PR TITLE
[TECHNICAL-SUPPORT] LPS-56446 Email message sent from Invitation portlet exposes the sender host's user name in the Message-ID header

### PR DESCRIPTION
**Pull request by IstvanD**
Hi Tibor,

Like you suggested in https://github.com/topolik/liferay-portal/pull/172#issuecomment-117190876 I resended the pull with using a random ID.

Cheers,
István

### CODE REVIEW

**Comment by lipusz** [comment]
Hi István,

I'm attending OSGi trainings today, so the review might be delayed. Sorry for it.

**Comment by IstvanD** [comment]
Hi Tibor,

No problem.

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Started reviewing...

**Comment by lipusz** [comment]
Forwarded to https://github.com/topolik/liferay-portal/pull/175
Thx!

**Pull request closed without merging**
