### PR TITLE
[TECHNICAL SUPPORT] LPS-83318 Sign in Portlet is maximized upon failed login, even when a full sized sign in portlet is on the page

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey @lipusz,

LPS:
https://issues.liferay.com/browse/LPS-83318

The issue: We maximize the login portlet upon failed login attempt, when there is already a full sized login portlet on the page. In this scenario, the failed login attempt should be displayed in the full sized login portlet without maximizing it to full screen.
See the SME request for further details regarding the expected and current behavior.
Please review the PR.

Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Hi Norbi,

Technically it's not a bug as the Web Content Display portlet is not removed, it's just a possible portlet rendering behavior to display in maximized mode.

While this may annoy your customer, but there can be others relying on that it's always rendered in maximized mode so it'd be a behavior change.

Also, I checked the LESA ticket and what they want is an answer how they can achieve the portlet not be rendered in maxmized mode, so they don't necessarily think it's a bug either.

I'd recommend them to follow https://dev.liferay.com/en/develop/tutorials/-/knowledge_base/7-0/overriding-mvc-commands#overriding-mvcactioncommand and override `com.liferay.login.web.internal.portlet.action.LoginMVCActionCommand` from the `login-web` module and change the code to work as they want. This is a supported customization method and I think this is what they need.

If you proceed like this, please close the LPS as Won't fix with this explanation.

Regards,
Tibi

**Comment by lipusz** [comment]
Related FR: https://issues.liferay.com/browse/LPS-49831

**Pull request closed without merging**
