### PR TITLE
LPS-65203

### PR DESCRIPTION
**Pull request by eperezg**
Hi Tibor, Could you please take a look alt this? Regards, Eduardo

### CODE REVIEW

**Comment by lipusz** [comment]
Please also start the workflow with the ticket: https://issues.liferay.com/browse/LPS-65203 :+1:

**Comment by eperezg** [comment]
Done,

Thanks!

**Comment by lipusz** [comment]
You just missed one step: you didn't assign it to me. I've done for you. ;-)

**Comment by lipusz** [comment]
Please, take a look at the test failures.

**Comment by eperezg** [comment]
Hi Tibor,

There are a couple of problems:
1.-[PMDTest.testPMDJava](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=1,label_exp=!master/2764//testReport/com.liferay.pmd/PMDTest/testPMDJava)
2.-[SourceFormatterTest.testSourceFormatter](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=4,label_exp=!master/2764//testReport/com.liferay.source.formatter/SourceFormatterTest/testSourceFormatter)

First one is related to the changes I made, the second one isn't, but I can fix it running format-source.
Should I fix both or only the first one?

**Comment by lipusz** [comment]
Hi Eduardo,

Only fix the 1st one. The 2nd should be gone away once the author fixes it
and you rebase your branch.

On Thu, Apr 21, 2016 at 5:19 PM, Eduardo Pérez García <
notifications@github.com> wrote:

> Hi Tibor,
>
> There are a couple of problems:
> 1.-PMDTest.testPMDJava
> <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=1,label_exp=!master/2764//testReport/com.liferay.pmd/PMDTest/testPMDJava>
> 2.-SourceFormatterTest.testSourceFormatter
> <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=4,label_exp=!master/2764//testReport/com.liferay.source.formatter/SourceFormatterTest/testSourceFormatter>
>
> First one is related to the changes I made, the second one isn't, but I
> can fix it running format-source.
> Should I fix both or only the first one?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/lipusz/liferay-portal/pull/121#issuecomment-212969002>
>



-- 

*Tibor Lipusz*

*Lead Software Engineer @ Platform TS, EMEA*

*SME of Search & Security, Subscription Services, Global*

*LSV Project Lead*


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

*Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

<http://www.liferay.com>

**Comment by eperezg** [comment]
I've closed this pull request and I'll send you a new one.

Thanks

**Pull request closed without merging**
