### PR TITLE
[TECHNICAL-SUPPORT] LPS-67452 StringUtil.splitLines(String) is inefficient

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-67452](https://issues.liferay.com/browse/LPS-67452)

Hi Tibi,

_SpringUtil.splitLines(String)_ is inefficient when we pass huge strings to it. In corner cases it may take ~15 minutes or even more. (See [LPS-67452](https://issues.liferay.com/browse/LPS-67452) for an example.)

The improvement is obvious even if we consider the password change scenario described on the LPS using the out-of-the-box _words.txt_ file:

| Environment | Execution time |
| --- | --- |
| Affected | 2100ms. |
| Fixed | 6ms. |

Thanks of reviewing,
Pisti

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Hi Pisti,

Can you please update your branch? Thanks!

**Comment by istvansajtos** [comment]
Hi Tibi,

I have just update it. Thank you!

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Forwarded to https://github.com/shuyangzhou/liferay-portal/pull/3111.
Thx! :+1:

**Pull request closed without merging**
