### PR TITLE
[TS] LPS-85702 IndexerPostProcessor not registered after restart

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-85702](https://issues.liferay.com/browse/LPS-85702)
Hi Tibi,

Please review my changes.

**Issue:**
Our our [DEV article](https://dev.liferay.com/en/develop/reference/-/knowledge_base/7-0/indexer-post-processor) has the following statement:

> indexer.class.name: the fully qualified class name of the indexed entity or an Indexer class itself.

In theory, this means that in an IndexerPostProcessor for MBMessage you can set _indexer.class.name_ attribute to either

- _com.liferay.message.boards.model.MBMessage_ (entity class name) or

- _com.liferay.message.boards.internal.search.MBMessageIndexer_ (indexer class name).

In practice, however, IndexerRegistryImpl doesn't handle this interchangeability well. When using the indexer class name, the post processor won't work after restart.

**Scenario 1:** IndexerPostProcessor module is deployed after portal startup.
During startup indexers are "registered" with both entity and indexer class name (in _IndexerRegistryImpl.register(Indexer)_). When the IndexerPostProcessor module is deployed, no matter which class name was used in its _indexer.class.name_ attribute, there will be a match (in _IndexerPostProcessor.addIndexerPostProcessor(IndexerPostProcessor, Map)_).

**Scenario 2:** Restarting the portal with IndexerPostProcessor deployed.
During startup the registration of IndexerPostProcessors may happen before the registration of Indexers (in _IndexerPostProcessor.addIndexerPostProcessor(IndexerPostProcessor, Map)_). If there is no corresponding Indexer registered yet, then the IndexerPostProcessor is queued with the given value of _indexer.class.name_ attribute. Later on, when the corresponding Indexer gets registered, the queue is queried for IndexerPostProcessor(s) with the entity class name only (in _IndexerRegistryImpl.register(Indexer)_).

Thank you,
Pisti

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hi Pisti, @istvansajtos 

Please look into the SF errors and adjust your code accordingly if needed.

Thank you!

**Comment by istvansajtos** [comment]
Hi Tibi, @lipusz

Sorry for the SF mistake. I've corrected it and also freshly rebased to master.

Thanks!

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by lipusz** [comment]
Thank you, Pisti!

**Comment by lipusz** [comment]
Hi Pisti,

The fix looks good, you can provide it in an SDH.

To proceed with the review, I'd like you to extend `IndexerPostProcessorRegistryTest` with a new test case to cover this bug. Let me know if you need help!

Thanks!

**Comment by istvansajtos** [comment]
Hi Tibi,

Great, thanks! I will return to this soon to extend with new test.

**Comment by lipusz** [comment]
Also, I adjusted the code a bit, see here: https://github.com/lipusz/liferay-portal/tree/pr-237-LPS-85702

https://github.com/lipusz/liferay-portal/compare/80f909e74187824d6d331c78e252efbfb28c372d...pr-237-LPS-85702

The most important part is this: lipusz@c8e1ee3

**Comment by lipusz** [comment]
Forwarded to https://github.com/mhan810/liferay-portal/pull/1435.
Please write the test and send me soon.

Thanks!

**Pull request closed without merging**
