### PR TITLE
[TS] LPS-71323 Display the editor user instead of the creator

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-71323](https://issues.liferay.com/browse/LPS-71323)

Hi Tibi,

Please review my changes.

*Issue:* DDLRecord type of assets always display the creator user as author while other type of assets display the editor user.

*Cause:* There is one DDLRecord for each new record, plus DDLRecordVersions for each modification (version) of it. DDLRecordAssetRenderer queries the user from DDLRecord, which refers to the creator, while the actual editor user is stored in DDLRecordVersions.

Thanks in advance,
Pisti

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by istvansajtos** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Pisti,

Please check if the test failures are related or not. Let me know if you need help. Thanks!

**Comment by lipusz** [comment]
Please rebase and retest. If it passes you can forward to Marcellus.

**Comment by istvansajtos** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:master

**Comment by lipusz** [comment]
Looks good. You can forward to Marcellus. :+1:

**Comment by istvansajtos** [comment]
Forwarded to [marcellustavares#1851](https://github.com/marcellustavares/liferay-portal/pull/1851)

**Pull request closed without merging**
