### PR TITLE
[TS] LPS-75058

### PR DESCRIPTION
**Pull request by ugurcancetin**
https://issues.liferay.com/browse/LPS-75058

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by ugurcancetin** [comment]
ci:retest

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Forwarded to https://github.com/dustinryerson/liferay-portal/pull/168.
Thanks! :+1:

**Pull request closed without merging**
