### PR TITLE
LPS-93762

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:search

**Comment by petershin** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
https://github.com/mhan810/liferay-portal/pull/1480

**Pull request closed without merging**
