### PR TITLE
LPS-65138 Allow all the types of the custom fields

### PR DESCRIPTION
**Pull request by hudakl**
https://issues.liferay.com/browse/LPS-65138

Hi,

A few types (short, Number), which could be custom fields were missed earlier.
I've added these types to the allowed list.

Could you please review the fix?

Thank you,
Laci

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Laci,

Just to make sure we won't need to push another set of changed for this, can you please verify that the current fix is enough to cover all possible types for ExpandoValue: https://github.com/agmip/liferay-portal-impl/blob/master/src/com/liferay/portlet/expando/service/impl/ExpandoValueLocalServiceImpl.java#L367-L466

Thanks!

**Comment by hudakl** [comment]
Hi,

In accordance with the ExpandoValueLocalServiceImpl I added the Date[] to the allow-list.

Thanks,
Laci

**Comment by lipusz** [comment]
Thank you, Laci!

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
Forwarded to https://github.com/matethurzo/liferay-portal/pull/1488
Thx! :+1:

**Pull request closed without merging**
