### PR TITLE
LPS-73210 Wait until there is some factory to parse configurations

### PR DESCRIPTION
**Pull request by csierra**
https://issues.liferay.com/browse/LPS-73210

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Carlos,

Thank you for helping us on this issue.
In order to learn from your solution, can you please explain why this change seems to be resolving the original report?

What we understand is that the `portal-configuration-extender` bundle is scanning the bundles becoming available and `NamedConfigurationPathContentFactory` is looking for that given manfiest header (`Liferay-Configuration-Path`), and if it finds any, it'll load all the `*.properties` and create a list of `NamedConfigurationContent` from them.

But why/how does changing the cardinality of the `NamedConfigurationContentFactory` `@Reference` in `com.liferay.portal.configuration.extender.internal.ConfiguratorExtender` from MULTIPLE to AT_LEAST_ONE has an impact on the issue?

I mean the `NamedConfigurationPathContentFactory` component is also provided by the `portal-configuration-extender` bundle so it should be available immediately, shouldn't it?

Thanks for guidance!

@csierra

**Comment by csierra** [comment]
> I mean the NamedConfigurationPathContentFactory component is also provided by the portal-configuration-extender bundle so it should be available immediately, shouldn't it?

not necessarily. Being an optional, dynamic and greedy dependency it is very likely that the component gets activated without having any factory injected, causing the activate method of the component to be run, causing the tracker to be activated, causing all bundles to be processed but, since at that point there is no injected factory yet, nothing is processed.
Just later the factory is injected but, at that point, the bundles have already been processed. 

In order for this to work we should find a way of securely rescan the bundles everytime a new factory is added to properly account for dynamic arrival of services. 
However, since now we only have one factory, we can just set _AT_LEAST_ONE_ to defer the activation until at least one factory is present, so no bundle is processed without a factory.

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Forwarded to https://github.com/tinatian/liferay-portal/pull/838.
Thanks, Carlos! :+1:

**Pull request closed without merging**
