### PR TITLE
[TS] LPS-88338 User can login using GET method on WebSphere

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-88338](https://issues.liferay.com/browse/LPS-88338)

Hi Tibi,

This is the continuation of https://github.com/lipusz/liferay-portal-ee/pull/357

Please see the LPS ticket for issue details.

About testing:
* I tested it on Liferay 7.0.x@b278844ef7f3b67b49a8b212d2eb5550547060b1 + Websphere 8.5.5.14.
* I couldn't deploy master on Websphere (tested with Websphere 8.5.5.14, 9.0.0.7, 9.0.0.10 (latest))

Feel free to find me with any questions.

Thank you,
Pisti

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
Hi Tibi, @lipusz

Do you have any news on this?

Thank you!

**Comment by lipusz** [comment]
See
https://issues.liferay.com/browse/LPS-88338?focusedCommentId=1733093&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1733093
.

**Pull request closed without merging**
