### PR TITLE
[TECHNICAL SUPPORT] LPS-65236 PortletSessionTracker causes memory leak and violates JSR 286 spec

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-65236

### CODE REVIEW

**Comment by lipusz** [comment]
Please, fix the test failures.

**Comment by lipusz** [comment]
Hi Norbi,

I think, you should just deprecate the class, not removing it.

**Comment by NorbertKocsis** [comment]
ci:retest

**Comment by NorbertKocsis** [comment]
Rebased on current master.

**Comment by NorbertKocsis** [comment]
ci:retest

**Comment by lipusz** [comment]
Sent for further review to Shuyang: https://github.com/shuyangzhou/liferay-portal/pull/2870

**Pull request closed without merging**
