### PR TITLE
[TS] LPS-72090 

### PR DESCRIPTION
**Pull request by ugurcancetin**
https://issues.liferay.com/browse/LPS-72090

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Ugur,

Please test if other parts of the same view are not affected and if so, please fix them also and update your pull! Thanks!

**Comment by ugurcancetin** [comment]
Hi @lipusz ,

There was another vulnerability on print_template.jsp 
I have updated it and tested as well. I couldn't see anything else as vulnerability related to KB on the other views. 

Thanks,
Ugurcan

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Forwarded to https://github.com/topolik/liferay-portal/pull/434
See my changes: https://github.com/lipusz/liferay-portal/commit/0ff33ef3628068ff7112ad544c72295ea1739d91

**Pull request closed without merging**
