### PR TITLE
[TS] LPS-98813

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-98813](https://issues.liferay.com/browse/LPS-98813)

Hi Tibi,

Please find the details on the LPS ticket.

The origin of the removed line of code is not completely clear for me, as it came from SVN about 10 years ago. Based on my observations we are not depending on it anymore and removing it doesn't cause any test failures.

Thank you,
Pisti

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
Hi Tibi, @lipusz 

As per my tests the change is safe, but please confirm it can be given out in an SDH.

Thank you,
Pisti

**Comment by lipusz** [comment]
ci:test:security

**Comment by lipusz** [comment]
ci:test:security

**Comment by lipusz** [comment]
**Started reviewing...** :mag::nerd_face:

**Comment by lipusz** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/76331.
I amended the commit message to be more informative.

Thanks! :+1:

**Pull request closed without merging**
