### PR TITLE
LPS-53685 Reviewer or Publisher is considered the author of a web content

### PR DESCRIPTION
**Pull request by achaparro**
Hi @lipusz, @akosthurzo,

Please read LPS-53685. To solve this it's necessary to revert the changes of LPS-45164, after that I was trying to reproduce the issue you solved to the find another solution however I wasn't able to reproduce it.

Could you take this pull request and give me the steps to reproduce the issue LPS-45164?

Thanks.
PS: Tibor, I couldn't find @akosthurzo in github so I have sent the pull request to you.
CC: @juliocamarero

### CODE REVIEW

**Comment by lipusz** [comment]
Hey Alberto, @akosthurzo

Both issue (based on the reproduction steps) seem valid, so you need to find a general solution.

**Comment by achaparro** [comment]
Hey Tibor,

Right but my question is, are you able to reproduce your issue using my
pull request? If so, the general solution is that.

Thanks.

On Friday, February 20, 2015, Tibor Lipusz <notifications@github.com> wrote:

> Hey Alberto, @akosthurzo <https://github.com/akosthurzo>
>
> Both issue (based on the reproduction steps) seem valid, so you need to
> find a general solution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lipusz/liferay-portal/pull/62#issuecomment-75205620>.
>


-- 
Alberto Chaparro

Engineer, Technical Support
Subscription Services | Spain and Portugal

Liferay Spain
Liferay Enterprise. Open Source. For Life.
Tel. +34 917336343

Próximos *cursos oficiales de Liferay*:
Mastering Liferay Fundamentals <https://www.regonline.com/mlf-mar-2015> - 2
y 3 de Febrero 2015, Madrid
Managing Content with Liferay <https://www.regonline.com/mcontent-feb-2015> -
4 y 5 de Febrero 2015, Madrid
Developing for the Liferay Platform 1
<https://www.regonline.com/dev1-Feb-2015> - 16 al 18 de Febrero 2015, Madrid
*Styling Liferay with Themes <https://www.regonline.com/themes-mar-2015>*
<https://www.regonline.com/themes-mar-2015>- 2 de Marzo de 2015, Madrid
*Administering Liferay Systems <https://www.regonline.com/als-mar-2015>* -
3 al 5 de Marzo 2015, Madrid
Developing for the Liferay Platform 1
<https://www.regonline.com/dev2-mar-2015> - 23 al 25 de Marzo 2015, Madrid

Visit Us: www.liferay.com  |  Like Us: facebook.com/liferay  |  Follow Us:
twitter.com/liferay_es

*Aviso de Confidencialidad: *Este mensaje de correo electrónico, incluidos
los archivos adjuntos, enviados en nombre de Liferay SL es para el uso
exclusivo del destinatario (s) previsto y puede contener información
confidencial y privilegiada. Se prohíbe cualquier revisión no autorizada,
uso, copia, divulgación o distribución. Si usted no es el destinatario, por
favor póngase en contacto con el remitente por correo electrónico de
respuesta y destruir todas las copias del mensaje original. Gracias.

*Confidentiality Notice: *This e-mail message, including any attachments,
sent on behalf of Liferay SL is for the sole use of the intended
recipient(s) and may contain confidential and privileged information. Any
unauthorized review, use, copying, disclosure or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply e-mail and destroy all copies of the original message. Thank
you.

**Comment by lipusz** [comment]
Got it.
I'm forwarding this to Ákos @akosthurzo, because I won't be able to check this in a reasonable time... Sorry for that.

https://github.com/akosthurzo/liferay-portal/pull/34

**Comment by achaparro** [comment]
Thanks @lipusz, I wanted to send the pull request to @akosthurzo yesterday since he made the changes but I couldn't.

Cheers.

**Pull request closed without merging**
