### PR TITLE
[TS] LPS-73622 ClassNotFoundException: com.liferay.portal.minifier.GoogleJavaScriptMinifier cannot be found when StripFilter set to false upon server startup

### PR DESCRIPTION
**Pull request by peterpetrekanics**
https://issues.liferay.com/browse/LPS-73622

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
Hi Petya,

Please,
1 rebase your branch to latest master
2 push with `-f`
3 Hit "ci:retest"

**Comment by peterpetrekanics** [comment]
ci:retest

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Pull request closed without merging**
