### PR TITLE
[Technical Support] LPS-72697

### PR DESCRIPTION
**Pull request by dustinryerson**
/cc @antonio-ortega

https://issues.liferay.com/browse/LPS-72697

Hey @lipusz, sending this through you for SME code review as Chema has informed us this is a Search Component decision rather than frontend: https://github.com/dustinryerson/liferay-portal/pull/140#issuecomment-303399584

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Guys,

I cannot reproduce it on master and in addition, the LPS indicates that the issue is not affecting master, though you sent this to me for master. :-)

Can you please clarify this?

Thanks!

@antonio-ortega @dustinryerson

**Comment by antonio-ortega** [comment]
Hi @lipusz ,

The issue is still reproducible in master but you need one of these two:
1.- Good eyesight. ;)
2.- Inspect the DOM elements to realice that:
 * "Any Asset", "Any Folder", "Any User", etc links has color #65B6F0 inherited from **text-primary** css class.
 * Only "Any Category" link has color #40a4ec applied to all **a** elements.

In DXP the issue is easier to catch because of the colors we use in that theme.

The root cause of the difference between "Any Categories" and the rest is a mistake defining the labels. In fact if you check  how this is defined for [asset_entries](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/portal-search/portal-search-web/src/main/resources/META-INF/resources/facets/view/asset_entries.jsp#L60-L62), [tags](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/portal-search/portal-search-web/src/main/resources/META-INF/resources/facets/view/asset_tags.jsp#L40-L42), [folders ](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/portal-search/portal-search-web/src/main/resources/META-INF/resources/facets/view/folders.jsp#L52-L54)you can see the same pattern I followed in this PR.

I hope this helps to clarify the issue, and I'll add "Master" to the affected versions in LPS.

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Forwarded to https://github.com/arboliveira/liferay-portal/pull/275.
Thanks!

Please send the backport for 70x once it's merged to master.

**Pull request closed without merging**
