### PR TITLE
[TS] LPS-71001 User enumeration is possible when users.reminder.queries.required enabled - work version

### PR DESCRIPTION
**Pull request by amadeafejes**
https://issues.liferay.com/browse/LPS-71001

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Ami,

Please fix the SF errors and fixup the changes into the related commit(s).

Thanks!

**Comment by amadeafejes** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi @amadeafejes 

There are still SF errors:
`[java] Move imports to init.jsp: ./modules/apps/foundation/login/login-web/src/main/resources/META-INF/resources/forgot_password.jsp`

Run either
`portal-impl: ant format-source-current-branch`
or
`login-web: gradlew formatSource`

to see the log locally.

**Comment by lipusz** [comment]
fixup the changes into to your last commit and name it "LPS-xxxx Auto SF"

**Comment by amadeafejes** [comment]
ci:retest

**Comment by amadeafejes** [comment]
ci:reopen

**Comment by lipusz** [comment]
#203

**Pull request closed without merging**
