### PR TITLE
LPS-73640 Customized Struts Action not applied after restart: StrutsActionRegistryUtil should use ServiceTrackerMap

### PR DESCRIPTION
**Pull request by csierra**
https://issues.liferay.com/browse/LPS-73640

/cc @rotty3000

### CODE REVIEW

**Comment by csierra** [comment]
hey @lipusz, 
this change should make _service.ranking. work now. Could you please retest it like you did and check this is actually working as expected?

Thanks a ton.

**Comment by lipusz** [comment]
Sure. I'll test it tomorrow.

Thanks, Carlos!

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Hi Carlos,

Actually, I cannot really test it because the steps described on the LPS no longer works on master since `EditDiscussionStrutsAction` has been deprecated in the core and moved to "comment-taglib" and the new one is not exported. And there is no other StrutsAction in the portal I could use to override this way. :-|

**Comment by csierra** [comment]
so it works 🎉 
😜

**Comment by lipusz** [comment]
:-)

So what to do?

**Comment by lipusz** [comment]
Can you send me a pull to ee-7.0.x so I could test it with the original steps?

**Comment by lipusz** [comment]
Hi Carlos,

I'd do this: reword the LPS to address the issue with service registration, not with my actual StrutsAction customization use-case which your changes have no impact on.

Or you could add a new test which proves that your fix works. @csierra

**Comment by lipusz** [comment]
Hi Carlos,

Did you happen to see my previous comment? @csierra

**Comment by lipusz** [comment]
Hi Carlos,

Did you happen to see my previous comment? @csierra

**Comment by csierra** [comment]
hey @lipusz 
I did... but unfortunately I am short of time lately. 
This pull will fix the general behavior of the tracker, which does not mean that we have hit any bug yet. 
Since there is nothing to fix for the moment I am fine leaving this pull here until it is needed (if ever). 
Bests.

**Comment by lipusz** [comment]
Rebased, fixed merge conflicts. https://github.com/lipusz/liferay-portal/tree/pull-request-188-LPS-73640

**Comment by lipusz** [comment]
Hi @csierra 

Please see https://issues.liferay.com/browse/LPS-73640?focusedCommentId=1201904&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1201904.

**Comment by lipusz** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/5320

**Comment by lipusz** [comment]
Thanks, Carlos!

**Pull request closed without merging**
