### PR TITLE
[TS] LPS-69935 PostgreSQL specific error is thrown when UserLocalServiceUtil#getSocialUsers() is called

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-69935](https://issues.liferay.com/browse/LPS-69935)
Hi Tibi,

This is the continuation of [#155](https://github.com/lipusz/liferay-portal/pull/155).

Hardcoding the table name into User*Comparator classed didn't work, because it resulted in incorrect syntax for other queries. Now I modify the ORDER BY cause where it indeed caused a problem and leave the comparator classes untouched.

Please let me know if you have any questions.

Thank you!
Pisti

### CODE REVIEW

**Comment by lipusz** [comment]
:+1: Elegant. :-)

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Hi Pisti,

You can remove the test portlet from the ticket. I've updated the steps to use a Groovy a script.

**Comment by istvansajtos** [comment]
Hi Tibi,

I've done it.

Thanks!

**Comment by lipusz** [comment]
https://github.com/istvansajtos/liferay-portal/pull/13

**Pull request closed without merging**
