### PR TITLE
LPS-52435 the scopeGroup for my account should be the group of the user

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by lipusz** [comment]
Hey @juliocamarero 

I get "You don't have the required permission to access this portlet" when

1- Private user layouts are disabled:
````properties
    layout.user.private.layouts.enabled=false
````
2- Start portal, navigate to "Navbar/My account/My Pages"

I did a double check with my branch, and it worked well. I'm looking into this.

**Comment by lipusz** [comment]
https://issues.liferay.com/secure/attachment/121175/pr-55-LPS-52435-julio.ogv

**Comment by juliocamarero** [comment]
ok, if it gets very complex we can just go with your initial solution....

**Comment by lipusz** [comment]
Your approach is smarter and there should be a solution for this "regression". I just need more time - I had an unplanned meeting today, so I didn't have time to work more on this-.

**Comment by lipusz** [comment]
The issue is caused by

````java
			Portlet myAccountPortlet = PortalUtil.getFirstMyAccountPortlet(
				themeDisplay);
````

in ServicePreAction.

For some reasons, themeDisplay.getScopeGroupId returns the groupId of the Global Group when I click on the "My Pages" tab in My Account.

I'm trying to figure out where this wrong groupId comes from... Any idea?

@juliocamarero

**Comment by lipusz** [comment]
Adding

````java
			urlControlPanelSitesPortlet = HttpUtil.setParameter(urlControlPanelSitesPortlet, "doAsGroupId", themeDisplay.getScopeGroupId());
````

to 

````java
			String urlControlPanelSitesPortlet = HttpUtil.setParameter(themeDisplay.getURLControlPanel(), "p_p_id", curPortletId);

			urlControlPanelSitesPortlet = HttpUtil.setParameter(urlControlPanelSitesPortlet, "controlPanelCategory", controlPanelCategory);

			urlControlPanelSitesPortlet = HttpUtil.setParameter(urlControlPanelSitesPortlet, "doAsGroupId", themeDisplay.getScopeGroupId());
````

https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/portal/layout/view/control_panel_nav_main.jspf

seems to solve the problem.

The background is that when we open the MyAccount portlet, it's like a ControlPanel scope, and

PortalImpl
````java
	@Override
	public long getScopeGroupId(
			HttpServletRequest request, String portletId,
			boolean checkStagingGroup)
		throws PortalException {
````

returns the groupId of the Global (Company) Group when "doAsGroupId" is not set in the request.

What do you think?

@juliocamarero

**Comment by juliocamarero** [comment]
I think that makes sense.

**Comment by lipusz** [comment]
Slight changes: 

control_panel.jsp defines

````jsp
		Group group = themeDisplay.getScopeGroup();

		if (group.isLayout()) {
			Layout scopeLayout = LayoutLocalServiceUtil.getLayout(group.getClassPK());

			group = scopeLayout.getGroup();
		}
		%>

		<div id="content-wrapper">
			<div class="<%= panelCategory %>">
				<c:if test="<%= showControlPanelMenu %>">
					<%@ include file="/html/portal/layout/view/control_panel_nav_main.jspf" %>
				</c:if>
````

before including that jspf, so "group.getGroupId()" should be used instead of "themeDisplay.getScopeGroupId()".

Two questions:
1- Should I set param "refererPlid", too, in the "urlControlPanelSitesPortlet"?
2- Do you want me to reorganize the commits and remove the unnecessary ones or leave it as is to let BChan get in context.

Thanks!

@juliocamarero

**Comment by juliocamarero** [comment]
Ok, makes sense.

1. we use that for the back link, but since my account is open in a popup we probably don't need it. Could you test it with dockbar.administrative.links.show.in.pop.up=false?

2. Yes, thanks! reorganize them in a way that make sense when reviewing by Brian.

Thank you!

**Comment by lipusz** [comment]
I've found that themeDisplay.getURLControlPanel() already contains param "refererPlid", so we don't need to set it again.

1- Tested, worked in both cases.
2- Will resend shortly.

**Comment by lipusz** [comment]
https://github.com/juliocamarero/liferay-portal/pull/3185

**Pull request closed without merging**
