### PR TITLE
[TS] LPS-72567 Indexer post processors throws NullPointerException after portal restart

### PR DESCRIPTION
**Pull request by peterpetrekanics**
https://issues.liferay.com/browse/LPS-72567
Indexer post processors throws NullPointerException after portal restart, this PR fixes this

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Petya,

Please, rebase your branch to latest master and re-push to your origin with `--force` option. Then, send a comment with content "ci:retest".

Thanks

**Comment by peterpetrekanics** [comment]
Hi Tibi,

All right I will do that right now,
Regards

**Comment by peterpetrekanics** [comment]
ci:retest

**Comment by lipusz** [comment]
Forwarded to https://github.com/arboliveira/liferay-portal/pull/272.
See my changes: https://github.com/lipusz/liferay-portal/compare/d049ef80ea098123701ac772c5c5b31b3c6c03ac...pull-request-178-LPS-72567

Thanks! :+1:

**Pull request closed without merging**
