### PR TITLE
[TS] LPS-77366 Replace RoleLocalServiceUtil with RoleServiceUtil to enforce permission checking

### PR DESCRIPTION
**Pull request by peterpetrekanics**
https://issues.liferay.com/browse/LPS-77366

Hi Tibi,

Please review my fix:

Manual testing shows that the fix correctly resolves the issue.

Thank you,
Peter

### CODE REVIEW

**Comment by peterpetrekanics** [comment]
ci:test

**Comment by lipusz** [comment]
@peterpetrekanics please pay attention to the changes I made next time you are sending a PR

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Hi Petya,

Even though the usage of "remote" service solved the permission checking problem, it may create a regression. Please see the screenshots I created before and after your changes:

**Before**
lps-77366-before

**After**
lps-77366-after

As you can see we unintentionally? filter out some related roles that a user (e.g. a Site Admin) should be able to view implicitly.

You may want to clarify the desired behavior with the WCM SME (Daniel Couso). From Security point of view I'm fine with the remote service call, though it'd cause a behavior change if we backport the fix as-is.

❓ **Are you sure the "after" state was the behavior on 7.0 or 6.2 before https://issues.liferay.com/browse/LPS-69542?**

@peterpetrekanics

**Comment by holatuwol** [comment]
@lipusz By default, both Portal Content Reviewer and Site Content Reviewer are only viewable by Owner, so the end result looks expected.

**Comment by lipusz** [comment]
@holatuwol

Still we should know if this was the exact behavior before the mentioned cause LPS.

If not, this fix would cause a behavior change.

I'm waiting for Péter's response.

**Comment by holatuwol** [comment]
@lipusz: I read your comment more closely. Conceptually, a Site Administrator should be able to see all the site roles since you can't remove their ability to do so in the UI. So I agree that if your screenshot is when testing as a Site Administrator, it does sound like the filtering doesn't actually work.

**Comment by lipusz** [comment]
Yes, both screenshots were created with Test1 user who has Site Admin role.

@holatuwol

**Pull request closed without merging**
