### PR TITLE
[TS] LPS-88004 Allow delete and update comments on Live site

### PR DESCRIPTION
**Pull request by vendeltoreki**
https://issues.liferay.com/browse/LPS-88004

Hi @lipusz ,

After PR https://github.com/danielkocsis/liferay-portal/pull/687, we discussed with @danielkocsis , and this solution seems to be acceptable from staging side. I used an override of `StagedModelPermissionLogic` for those entities, where comments can be actually added. I've checked the `*PermissionRegistrar` classes and found these:
* [BlogsEntry](https://github.com/liferay/liferay-portal/blob/65059440dfaf2b8b365a20f99e83e4cdb15478aa/modules/apps/blogs/blogs-service/src/main/java/com/liferay/blogs/internal/security/permission/resource/definition/BlogsEntryModelResourcePermissionDefinition.java)
* [DLFileEntry](https://github.com/liferay/liferay-portal/blob/61ba1ec88bfc5799a1c0dbcc849bda7dc3eb662a/modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/security/permission/resource/DLFileEntryModelResourcePermissionRegistrar.java)
* [JournalArticle](https://github.com/liferay/liferay-portal/blob/ad87fa7d1008e58825e7ac0e1b6d8c1104671d2b/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/security/permission/resource/JournalArticleModelResourcePermissionRegistrar.java)
* [WikiPage](https://github.com/liferay/liferay-portal/blob/ad87fa7d1008e58825e7ac0e1b6d8c1104671d2b/modules/apps/wiki/wiki-service/src/main/java/com/liferay/wiki/internal/security/permission/resource/WikiPageModelResourcePermissionRegistrar.java)

Also updated Layout - `LayoutPermissionImpl` as per the discussion on this ticket and over Google Chat.

Please review my changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Can you please check if we have any modules in master-private which might also be affected? Thanks!

**Comment by vendeltoreki** [comment]
I've just checked the master-private branch, but haven't found any staging related permission logic.

**Comment by lipusz** [comment]
Thanks @vendeltoreki ! :+1:

**Comment by lipusz** [comment]
See https://issues.liferay.com/browse/LPS-88004?focusedCommentId=1641131&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1641131

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Hey @vendeltoreki 

Based on the `*/resource-actions/*.xml` definitions,
* CalendarBooking (`modules/apps/calendar/calendar-service/src/main/resources/META-INF/resource-actions/default.xml`)
* Layouts (`/portal-master/portal-impl/src/resource-actions/sites.xml`)
* and TasksEntry (`modules/apps/tasks/tasks-portlet/docroot/WEB-INF/src/resource-actions/default.xml`)

also support `*_DISCUSSION` permissions.

Can you please check and update the related `*PermissionRegistrar` classes if these entities are also relevant from Staging perspective?

Thanks!

**Comment by lipusz** [comment]
Please also take a look at my comments on the LPS. Thanks!

**Comment by vendeltoreki** [comment]
Hi @lipusz ,

Thanks for the detailed analysis. I checked the remaining entries:
* **CalendarBooking** uses a different approach for checking comment permissions in staging. It is working correctly already.
* **Layout** permissions are handled in [`LayoutPermissionImpl`](https://github.com/liferay/liferay-portal/blob/10d13cdcfea1557d144617c1d5d92fde962af6f6/portal-impl/src/com/liferay/portal/service/permission/LayoutPermissionImpl.java#L555) in `portal-impl`. I added a new [commit](https://github.com/lipusz/liferay-portal/pull/241/commits/654d2a56d4fceda79c4f691bee1d427f552e9e82) to change this as well. It simply skips the StagingPermission check for UPDATE/DELETE_DISCUSSION actions. It is possible to do it this way, since in this case, [`StagingPermissionImpl`](https://github.com/liferay/liferay-portal/blob/ad87fa7d1008e58825e7ac0e1b6d8c1104671d2b/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/staging/permission/StagingPermissionImpl.java#L81) only makes decisions based on the `actionId`. So by skipping it, we don't skip any further permission checks. At least that's my theory but I might be wrong.
* **TaskEntry** is not staged at all, so there's no need to control permissions from staging perspective.

Please review my new change.

Thanks,
Vendel

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Forwarded to https://github.com/adolfopa/liferay-portal/pull/786.
Thanks! :+1:

**Pull request closed without merging**
