### PR TITLE
[TS] LPS-88338

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-88338](https://issues.liferay.com/browse/LPS-88338)

Hi Tibi,

Please see the LPS ticket for details.

(i) I tested it on Liferay 7.0.x + Websphere 8.5.5.14. My attempts to deploy portal master on Websphere failed. (Tested with Websphere 8.5.5.14, 9.0.0.7, 9.0.0.10 (latest))

Feel free to find me with any questions.

Thank you,
Pisti

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
See comment on the ticket.

**Pull request closed without merging**
