### PR TITLE
[TS] LPS-73087

### PR DESCRIPTION
**Pull request by ugurcancetin**
Hi @lipusz,

https://issues.liferay.com/browse/LPS-73087

I got the information from Nimrod that this is a bit urgent for the customer. I wanted to let you know about this also.
Thanks!!

### CODE REVIEW

**Comment by ugurcancetin** [comment]
ci:retest

**Comment by ugurcancetin** [comment]
ci:reopen

**Comment by lipusz** [comment]
Hi Ugur,

Can you please rebase to latest master and hit a ci retest? Thanks!

**Comment by ugurcancetin** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi @ugurcancetin ,

Please remove the unnecessary import from `CreateAccountMVCActionCommand` which causes the SF test failures and update the pull. Thanks!

**Comment by ugurcancetin** [comment]
Hi @lipusz,
Sorry for that, my bad :+1: .

**Comment by ugurcancetin** [comment]
ci:retest

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
https://github.com/topolik/liferay-portal/pull/446
Thanks! :+1:

**Comment by lipusz** [comment]
Please also send the backports for 70x & 62x once it's merged to master.

**Pull request closed without merging**
