### PR TITLE
LPS-91722 Check permission against the group we render

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-91722](https://issues.liferay.com/browse/LPS-91722)

Hi Tibi,

The issue is somewhat related to [LPS-87399](https://issues.liferay.com/browse/LPS-87399) where a permission check was introduced before rendering the site settings. It turned out that the permission check still can be bypassed when the URL doesn't  supply the _groupId_. 

As a solution, I examined how we determine the group to render when the URL lacks the _groupId_ parameter (_edit_site.jsp_) and used the same approach (i.e. _themeDisplay.getScopeGroupId()_) here.

It is worth checking the LPP, because I recorded some details there that might help the understanding.

Please, feel free to ask me any time if it ease your work.

Thank you in advance,
Pisti

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hi Pisti,

Please send this to the SME of the area or the engineering lead of the component.

Thanks,
Tibi

**Comment by lipusz** [comment]
ci:stop

**Comment by istvansajtos** [comment]
Thanks for the quick feedback, Tibi! I will proceed as you requested.

**Pull request closed without merging**
