### PR TITLE
[TS] LPS-69762 Unable to include .tpl file in a layout template

### PR DESCRIPTION
**Pull request by ugurcancetin**
https://issues.liferay.com/browse/LPS-69762

### CODE REVIEW

**Comment by ugurcancetin** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
Hi Ugur,

Please fix the Source Formatting (SF) error:
```
 [java] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/template/URLResourceParser.java
     [java] Private static non-final field '_ALLOWED_FILE_EXTENSIONS' must match pattern '^_[a-z0-9][_a-zA-Z0-9]*$': ./portal-impl/src/com/liferay/portal/template/URLResourceParser.java 181
     [java] Exception in thread "main" java.lang.Exception: Private static non-final field '_ALLOWED_FILE_EXTENSIONS' must match pattern '^_[a-z0-9][_a-zA-Z0-9]*$': ./portal-impl/src/com/liferay/portal/template/URLResourceParser.java 181
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:264)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:167)
```

Looks like we violated the allowed pattern for names for static non-final variables. Instead of ```_ALLOWED_FILE_EXTENSIONS``` try ```_allowedFileExtensions```. Modify, compile (```portal-impl: ant deploy```), then run ```ant format-source``` again from portal-impl.

Then
- commit the additional change
- ask me to help to do an interactive rebase to "fixup" this last commit into the one in which you originally modified the URLResourceParser file.
- Update your branch in your origin: ```git push --force origin HEAD```

Don't forget to checkout your LPS-xxxx branch. ;-)

@ugurcancetin

**Comment by ugurcancetin** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by ugurcancetin** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by ugurcancetin** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Ugur,

Please do this:
- checkout your branch
- delete master: ```git branch -D master```
- fetch master: ```git fetch --no-tags upstream master:master```
- create a new branch based on master: ```git checkout -b LPS-69762-2 master```
- cherry-pick your commits from your old branch
- push to your origin
- send a new pull to me

Looks like something is wrong in your branch that's why CI is failing. Thanks!

**Comment by ugurcan2020** [comment]
Hi Tibi,

As far as I see, you are totally right :)
I will be fallowing your instructions tomorrow .

Thanks for your help !!!

**Comment by lipusz** [comment]
https://github.com/lipusz/liferay-portal/pull/158

**Pull request closed without merging**
