### PR TITLE
[TS] LPS-78119 Web Content fields behave inconsistently when searched

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-78119](https://issues.liferay.com/browse/LPS-78119)

Hi Tibi,

I'm sending this as the continuation of #220 which couldn't be reopened due to force-push.

Thank you,
Pisti

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Hi Pisti,

Looks like you don't see for some reasons the inline comments I added to `JournalArticleIndexer` and `BaseIndexer`.

So when you try to determine the `groupId` it may not work in all cases.

What if the "scope" is set by the ScopeFacet? So when I search I can decide which sites to search in (Any Site or selected site).

Also, the new Search Portlet in Master enables to search in multiple sites (multi facet selection) so the list of available language ids can be the "merge" of the individual group available language ids.

I think this code has to be changed to cover these cases.

**Comment by lipusz** [comment]
Hi Pisti,

I've discussed this with the team.

Basically, 
so basically, check if `searchContext.getGroupIds()` has a groupId and use that in `LanguageUtil.getAvailableLocales(groupId)`, otherwise just use `LanguageUtil.getAvailableLocales()`

should do the trick no other things should be considered.

Also,  ScopeFacet will be deprecated soon so can be ignored.

Thirdly, we should extend the current test cases to cover the expected behavior.

Please find me if you need further help to update your code.

**Comment by istvansajtos** [comment]
I sent new PR with the requested changes. Please see https://github.com/lipusz/liferay-portal/pull/222

**Pull request closed without merging**
