### PR TITLE
[TS] LPS-42478 Blob data may reveal Hibernate issue HHH-8310

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-42478](https://issues.liferay.com/browse/LPS-42478)

Hi Tibi,

I am sending this according to our discussion. The linked ticket contains the descreption of the issue and the reproduction steps. 

Please let me know if you need anything else.

Thank you,
Pisti

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
Please, fix the related errors and update your branch. Thanks!

**Comment by istvansajtos** [comment]
Tibi, I have updated my branch. It should pass the tests now.

**Comment by istvansajtos** [comment]
ci:retest

**Comment by istvansajtos** [comment]
ci:retest

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Forwarded to https://github.com/shuyangzhou/liferay-portal/pull/3896.
Thank you Pisti for the efforts you put into this! :+1: :1st_place_medal:

**Pull request closed without merging**
