### PR TITLE
Test Elasticsearch 6.8 upgrade with X-Pack tests | Client: 6.5.0 Server: 6.8.2

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-98247

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by xbrianlee** [comment]
FYI changes in this PR might conflict with changes from https://github.com/brianchandotcom/liferay-portal/pull/76588 once it's in upstream

**Pull request closed without merging**
