### PR TITLE
[TS] LPS-69369 Setting virtual host for private page breaks site control p…

### PR DESCRIPTION
**Pull request by rimisaadouwork**
https://issues.liferay.com/browse/LPS-69369

Hi,
I did some refactoring. Please review this commit.

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
Hi Rimi,

Please use the LPS number also as a branch name next time.

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
ci:retest

**Comment by rimisaadouwork** [comment]
cit:test

**Comment by lipusz** [comment]
@
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Hi Rimi,

Sorry for not responding earlier. There are many things on my plate right now, but I'll try to proceed with this tomorrow or on Friday as a latest.

**Comment by lipusz** [comment]
Hi Rimi,

I have to work on the security release this week, so please, forward to the SME of the Core Infrastructure team, https://github.com/jonathanmccann.

Thanks and sorry for not updating you earlier.

**Pull request closed without merging**
