### PR TITLE
[TS] LPS-109095 Elasticsearch bulk execution failures are not logged properly

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-109095](https://issues.liferay.com/browse/LPS-109095)

Hi Tibi,

Please review my changes. It should be in line with the info that came from the product team and what you shared on PTR.

Please let me know if there is anything I can do for you.

Thank you,
Pisti

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by lipusz** [comment]
@istvansajtos Doesn't it affect the portal-search-elasticsearch7 connector, too?

**Comment by lipusz** [comment]
As I can see it does. Can you please apply your fix to the es7 connector too? Thanks!

**Comment by istvansajtos** [comment]
> As I can see it does. Can you please apply your fix to the es7 connector too? Thanks!

Yeah, I was even thinking about it. I don't know how I forgot it eventually. :) Thanks for catching!

**Comment by istvansajtos** [comment]
ci:test:relevant:norebase

**Comment by istvansajtos** [comment]
ci:test:search:norebase

**Comment by istvansajtos** [comment]
ci:help

**Comment by istvansajtos** [comment]
ci:test:search-es7:norebase

**Comment by lipusz** [comment]
I don't see unique failures based on https://docs.google.com/spreadsheets/d/1cDzu4itg1XPtK4EyuwWB3MBwK3m7MpT3LqLcXltx9QA/edit?pli=1#gid=0

**Comment by lipusz** [comment]
ci:test:search:55c45e541fc40f21481c3be233892a9e21029e76

**Comment by lipusz** [comment]
ci:test:search-es7:55c45e541fc40f21481c3be233892a9e21029e76

**Comment by istvansajtos** [comment]
Hi Tibi, @lipusz 

What do you think about the changes? Safe enough to give out in a hotfix?

Thank you,
Pisti

**Comment by lipusz** [comment]
Ah, yes, absolutely. :+1:

**Comment by lipusz** [comment]
ci:test:search-es7:235df4cb7357fbc4116c0240ffef7e03fb0fd0f0

**Comment by lipusz** [comment]
Hi Pisti,

As I can see there are no unique failures based on, so feel free to forward this to Bryan. Please rebase your branch on the latest stable search has from https://search-ci.liferay.com/.

Thanks!

**Pull request closed without merging**
