### PR TITLE
[TS] LPS-87555 DLFileEntries are not retrieved when using searchContext.setIncludeAttachments(true)

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-87555](https://issues.liferay.com/browse/LPS-87555)

Hi Tibi,

As we discussed before, searchContext.setIncludeAttachments(true) should not exclude regular DLFileEntries from the search results. Please review my fix and let me know what you think.

Additional info:
* I am also cleaning up temporary Wiki attachments similarly to [how it was handled by LPS-77260 for MessageBoard in EditMessageMVCActionCommand](https://github.com/brianchandotcom/liferay-portal/pull/55333/commits/219d933afbb05ffd0926005603e3faca4a55eb9e)
* I am using FacetedSearcher in the test. First I wanted to use IndexerSearcher as the case doesn't really use facets, but using IndexerSearcher the relatedEntryClassNames attribute is always set, resulting in test failures (like the infinite loop I mentioned to you) and also too restrictive pre filters for the attachment search scenario.

You know where to find me if you want to talk about this.

Thank you,
Pisti

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:search

**Comment by istvansajtos** [comment]
ci:test:search

**Comment by istvansajtos** [comment]
ci:test:search

**Comment by istvansajtos** [comment]
The test failures are unrelated.

**Comment by lipusz** [comment]
Hey Pisti,

Go ahead and provide it in an SDH if it solves the customer's use case. I'll try to proceed with this next, but currently I'm busy with other things.

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:search

**Comment by istvansajtos** [comment]
ci:test:search

**Comment by lipusz** [comment]
Retesting here: https://github.com/lipusz/liferay-portal/pull/246 maybe there is a problem with CI search.

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
Hi @istvansajtos 

Can you please fix the conflict and rebase?

**Comment by istvansajtos** [comment]
Hi Tibi, @lipusz 

I'm on it. I will update the PR soon.

**Comment by istvansajtos** [comment]
I removed the commit handling the undeleted wiki attachments, because the same was fixed by [LPS-89887](https://issues.liferay.com/browse/LPS-89887) in the meantime.

**Comment by istvansajtos** [comment]
ci:test:search

**Comment by lipusz** [comment]
Hey @istvansajtos 

This failure 
    1. [LocalFile.Search#SearchDocumentsAndMediaDocument](https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/270101//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_SearchDocumentsAndMediaDocument_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/test-1-18/1550585395519/test-portal-acceptance-pullrequest(master)/478/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.Search_SearchDocumentsAndMediaDocument/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/test-1-18/1550585395519/test-portal-acceptance-pullrequest(master)/478/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.Search_SearchDocumentsAndMediaDocument/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/test-1-18/1550585395519/test-portal-acceptance-pullrequest(master)/478/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz)

might be related to your change.

Here is the test case: https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase#L861

Can you please check?

Thanks, Pisti!

**Comment by istvansajtos** [comment]
Hi Tibi @lipusz,

I'll take care of it.

**Comment by istvansajtos** [comment]
Hi Tibi @lipusz ,

I could reproduce the same without my commits, so it is not related.

**Comment by istvansajtos** [comment]
ci:test:search

**Comment by lipusz** [comment]
Hey Pisti, @istvansajtos 

When I run the new test locally (```gradlew testIntegration --tests *AttachmentSearchTest```) I get

```
com.liferay.portal.search.test.AttachmentSearchTest > testSearchIncludeAttachment FAILED
    java.lang.AssertionError: [{entryClassPK=[36852], ddm__text__25051__HttpHeaders_CONTENT_TYPE_en_US_String_sortable=[text/plain; charset=iso-8859-1], localized_title_sv_SE=[gvetrseb], groupId=[20126], publishDate=[19700101010000], mimeType=[application_vnd.openxmlformats-officedocument.wordprocessingml.document], classNameId=[22002], createDate_sortable=[1551195024894], readCount=[0], localized_title_nl_NL=[gvetrseb], path=[gveTrseb], classPK=[36843], localized_title_zh_CN=[gvetrseb], scopeGroupId=[20126], modified=[20190226163024], localized_title_ar_SA_sortable=[gvetrseb], modified_sortable=[1551195024901], localized_title_pt_BR=[gvetrseb], localized_title_ca_ES_sortable=[gvetrseb], mimeType_String_sortable=[application_vnd.openxmlformats-officedocument.wordprocessingml.document], content_en_US=[Content: Enterprise. Open Source. For Life.], localized_title_zh_CN_sortable=[gvetrseb], localized_title_ca_ES=[gvetrseb], localized_title_hu_HU_sortable=[gvetrseb], visible=[false], localized_title_nl_NL_sortable=[gvetrseb], fileEntryTypeId=[0], priority=[0.0], classTypeId=[0], folderId=[36851], ddm__text__25051__HttpHeaders_CONTENT_TYPE_en_US=[text/plain; charset=ISO-8859-1], companyId=[20099], size=[43], localized_title_fr_FR=[gvetrseb], nodeId=[36841], status=[0], localized_title_hu_HU=[gvetrseb], localized_title_pt_BR_sortable=[gvetrseb], publishDate_sortable=[0], hidden=[true], dataRepositoryId=[36851], localized_title_fi_FI_sortable=[gvetrseb], relatedEntry=[true], title=[gveTrseb], uid=[com.liferay.document.library.kernel.model.DLFileEntry_PORTLET_36852], localized_title_de_DE_sortable=[gvetrseb], localized_title_en_US_sortable=[gvetrseb], groupRoleId=[20126-20114], localized_title_fr_FR_sortable=[gvetrseb], ddm__text__25051__HttpHeaders_CONTENT_ENCODING_en_US=[ISO-8859-1], title_sortable=[gvetrseb], expirationDate_sortable=[9223372036854775807], localized_title_sv_SE_sortable=[gvetrseb], localized_title_ja_JP=[gvetrseb], localized_title_fi_FI=[gvetrseb], size_sortable=[43], createDate=[20190226163024], expirationDate=[99950812133000], localized_title_es_ES_sortable=[gvetrseb], entryClassName=[com.liferay.document.library.kernel.model.DLFileEntry], roleId=[20106, 20107], ddm__text__25051__HttpHeaders_CONTENT_ENCODING_en_US_String_sortable=[iso-8859-1], userName=[test test], userId=[20139], localized_title_ja_JP_sortable=[gvetrseb], localized_title=[gvetrseb], stagingGroup=[false], localized_title_es_ES=[gvetrseb], localized_title_en_US=[gvetrseb], localized_title_ar_SA=[gvetrseb], ddmContent=[text/plain; charset=ISO-8859-1 ISO-8859-1], properties=[gveTrseb], treePath=[, 36847, 36850, 36851], localized_title_de_DE=[gvetrseb]}}, length=1, query=null] expected:<2> but was:<1>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at com.liferay.portal.search.test.AttachmentSearchTest.assertSearchIncludeAttachment(AttachmentSearchTest.java:111)
        at com.liferay.portal.search.test.AttachmentSearchTest.testSearchIncludeAttachment(AttachmentSearchTest.java:80)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.arquillian.extension.junit.bridge.statement.ServerExecutorStatement$1.evaluate(ServerExecutorStatement.java:69)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
        at com.liferay.portal.test.rule.LiferayIntegrationTestRule$1$1.evaluate(LiferayIntegrationTestRule.java:154)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$3.evaluate(BaseTestRule.java:110)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$3.evaluate(BaseTestRule.java:110)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$3.evaluate(BaseTestRule.java:110)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$3.evaluate(BaseTestRule.java:110)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$3.evaluate(BaseTestRule.java:110)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$3.evaluate(BaseTestRule.java:110)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$3.evaluate(BaseTestRule.java:110)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$3.evaluate(BaseTestRule.java:110)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$3.evaluate(BaseTestRule.java:110)
        at com.liferay.portal.test.rule.LiferayIntegrationTestRule$1$1.evaluate(LiferayIntegrationTestRule.java:154)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$3.evaluate(BaseTestRule.java:110)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.liferay.arquillian.extension.junit.bridge.statement.ServerExecutorStatement.evaluateWithClassRule(ServerExecutorStatement.java:164)
        at com.liferay.arquillian.extension.junit.bridge.statement.ServerExecutorStatement.evaluate(ServerExecutorStatement.java:130)
        at com.liferay.arquillian.extension.junit.bridge.junit.Arquillian._runMethod(Arquillian.java:214)
        at com.liferay.arquillian.extension.junit.bridge.junit.Arquillian.access$200(Arquillian.java:56)
        at com.liferay.arquillian.extension.junit.bridge.junit.Arquillian$1.evaluate(Arquillian.java:116)
        at com.liferay.arquillian.extension.junit.bridge.junit.Arquillian.run(Arquillian.java:95)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at com.liferay.arquillian.extension.junit.bridge.jmx.JMXTestRunner.runTestMethod(JMXTestRunner.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
        at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
        at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
        at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
        at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
        at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
        at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
        at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
        at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Can you please look into this?

**Comment by lipusz** [comment]
There were too many failures and comments on this PR and look like there may be a rebase conflict, so it's better if you resend. Thanks! :+1:

**Comment by lipusz** [comment]
Regarding the new test, as it's for collaboration only, I'd put it into the document-library service test if all dependencies (boilerplate code) you need is available there.

It should be sent to Adolfo too for review.

**Pull request closed without merging**
