### PR TITLE
[TS] LPS-73641 

### PR DESCRIPTION
**Pull request by ugurcancetin**
Hi Tibi,

This solves the issue as discussed and I have tested it manually with different use-cases, it didn't fail.
https://issues.liferay.com/browse/LPS-73641

Thanks for your help,
Ugurcan

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by ugurcancetin** [comment]
Hi @lipusz,
I rebased the fix top on master. 

Thanks

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Please update and retest. Thanks! @ugurcancetin

**Comment by ugurcancetin** [comment]
ci:retest

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by ugurcancetin** [comment]
ci:retest

**Comment by ugurcancetin** [comment]
ci:retest

**Comment by lipusz** [comment]
https://github.com/arboliveira/liferay-portal/pull/317

**Pull request closed without merging**
