### PR TITLE
LPS-67560

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi Tibor,

Please, review this PR. You can find further information in [LPS-67560](https://issues.liferay.com/browse/LPS-67560) and [the thread](https://in.liferay.com/web/support/forums/-/message_boards/message/24217250) where we discussed it.

Regards,

### CODE REVIEW

**Comment by lipusz** [comment]
Hi @antonio-ortega 

Please look at the SF-related failure and update your branch accordingly.

Thx!

**Comment by antonio-ortega** [comment]
ci:retest

**Comment by lipusz** [comment]
Can you please rebase it to latest

**Comment by lipusz** [comment]
Hi Antonio,

We cannot put such logic into the code that assumes the existence of a specific vendor. It goes against the modularization and separation of concerns.

If we need a logic that is required only for Solr, then it should go into our portal-search-sorl module.

**Comment by antonio-ortega** [comment]
Hi Tibor,

That makes sense completely, and this is one of the reasons why in [the first question I asked](https://in.liferay.com/web/support/forums/-/message_boards/message/24217250#_19_message_24217250) in support forums I was talking about another kind of solution, which changes would be into **portal-search-solr** (to be exact, in com.liferay.portal.search.solr.internal.query.**SolrQueryTranslator.translate**(Query, SearchContext). But my concern was I needed to recover part of the code that had been removed in [LPS-50968](https://issues.liferay.com/browse/LPS-50968) and [LPS-54881](https://issues.liferay.com/browse/LPS-54881), and I am not sure if this idea is right, especially seeing LPS-50968.

Do you think we should recover the "adjust Query" process for Solr or there is a better and cleaner solution?

Thanks!

**Pull request closed without merging**
