### PR TITLE
[TS] LPS-104673

### PR DESCRIPTION
**Pull request by hudakl**
https://issues.liferay.com/browse/LPS-104673

Hi,

Based on our discussion, I prepared the fix for LPS-104673.
Could you please review my changes?

Thanks,
Laci

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf:norebase

**Comment by lipusz** [comment]
ci:test:relevant:norebase

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by lipusz** [comment]
Hi Laci, @hudakl 

Can you please take a look at the failures? To decide if they are related, you can check the "known test failures" in https://search-ci.liferay.com/.

Thanks!

**Comment by hudakl** [comment]
I'm afraid, the test failures are relevant, they only affect my branch and the master it is based on. I'm investigating what goes wrong.

**Pull request closed without merging**
